-- phpMyAdmin SQL Dump
-- version 3.2.0.1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Jan 01, 2011 at 08:31 PM
-- Server version: 5.1.37
-- PHP Version: 5.2.11

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `trainReservation`
--

-- --------------------------------------------------------

--
-- Table structure for table `train_schedule`
--

CREATE TABLE `train_schedule` (
  `trainNo` varchar(5) NOT NULL,
  `trainName` varchar(50) NOT NULL,
  `departureStation` varchar(20) NOT NULL,
  `departureTime` time NOT NULL,
  `arrivalStation` varchar(20) NOT NULL,
  `arrivalTime` time NOT NULL,
  `stationsIncluded` varchar(1000) NOT NULL,
  `frequency` varchar(50) NOT NULL,
  `otherInformation` varchar(200) NOT NULL,
  PRIMARY KEY (`trainNo`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `train_schedule`
--

INSERT INTO `train_schedule` VALUES('0005', 'Podi Menike', 'Colombo-Fort', '05:55:00', 'Badulla', '16:20:00', 'Colombo-Fort, Maradana, Dematagoda, Kelaniya, Wanawasala, Hunupitiya, Enderamulla, Horape, Ragama, Walpola, Batuwaththa, Bulugahagoda, Ganemulla, Yagoda, Gampaha, Daraluwa, Bemmulla, Magalegoda, Heendeniya Pattiyagoda, Veyangoda, Wadurawa, Keenawala, Ganegoda, Wijaya Rajadahana, Mirigama, Wilwatta, Botale, Ambepussa, Yattalgoda, Bujjomuwa, Alawwa, Walakumbura, Polgahawela, Panaliya, Tismalpola, Yatagama, Rambukkana, Kadigamuwa, Gangoda, Ihala Kotte, Balana, Kadugannawa, Pilimatalawa, Peradeniya, Gampola, Ulapane, Nawalapitiya, Galabodde, Watawala, Rozella, Hatton, Kotagala, Talawakelle, Watagodde, Great Western, Nanu Oya, Ambewela, Pattipola, Ohiya, Idalgashinna, Haputale, Diyatalawe, Bandarawela, Ella, Demodara, Uduwara, Hali Ela, Badulla.', 'Daily', 'Runs Via Kandy, Observation Saloon 2nd & 3rd Class');
INSERT INTO `train_schedule` VALUES('0006', 'Podi Menike', 'Badulla', '09:10:00', 'Colombo-Fort', '19:45:00', 'Badulla, Hali Ela, Uduwara, Demodara, Ella, Bandarawela, Diyatalawe, Haputale, Idalgashinna,  Ohiya, Pattipola, Ambewela, Nanu Oya, Great Western, Watagodde, Talawakelle, Kotagala, Hatton, Rozella, Watawala, Galabodde, Nawalapitiya, Ulapane, Gampola, Peradeniya, Pilimatalawa, Kadugannawa, Balana, Ihala Kotte, Gangoda, Kadigamuwa, Rambukkana, Yatagama, Tismalpola, Panaliya, Polgahawela, Walakumbura, Alawwa, Bujjomuwa, Yattalgoda, Ambepussa, Botale, Wilwatta, Mirigama, Wijaya Rajadahana, Ganegoda, Keenawala, Wadurawa, Veyangoda, Heendeniya Pattiyagoda, Magalegoda, Bemmulla, Daraluwa, Gampaha, Yagoda, Ganemulla, Bulugahagoda, Batuwaththa, Walpola, Ragama, Horape, Enderamulla, Hunupitiya, Wanawasala, Kelaniya, Dematagoda, Maradana, Colombo-Fort', 'Daily', 'Runs via Kandy, Observation Saloon 2nd & 3rd Class');
INSERT INTO `train_schedule` VALUES('0009', 'Intercity Express', 'Colombo-Fort', '07:00:00', 'Kandy', '09:35:00', 'Colombo-Fort, Maradana, Dematagoda, Kelaniya, Wanawasala, Hunupitiya, Enderamulla, Horape, Ragama, Walpola, Batuwaththa, Bulugahagoda, Ganemulla, Yagoda, Gampaha, Daraluwa, Bemmulla, Magalegoda, Heendeniya Pattiyagoda, Veyangoda, Wadurawa, Keenawala, Ganegoda, Wijaya Rajadahana, Mirigama, Wilwatta, Botale, Ambepussa, Yattalgoda, Bujjomuwa, Alawwa, Walakumbura, Polgahawela, Panaliya, Tismalpola, Yatagama, Rambukkana, Kadigamuwa, Gangoda, Ihala Kotte, Balana, Kadugannawa, Pilimatalawa, Peradeniya, Sarasavi Uyana, Kandy', 'Daily', '1st & 2nd Class Reserved');
INSERT INTO `train_schedule` VALUES('0010', 'Intercity Express', 'Kandy', '15:00:00', 'Colombo-Fort', '17:35:00', 'Kandy, Sarasavi Uyana, Peradeniya, Pilimatalawa, Kadugannawa, Balana, Ihala Kotte, Gangoda, Kadigamuwa, Rambukkana, Yatagama, Tismalpola, Panaliya, Polgahawela, Walakumbura, Alawwa, Bujjomuwa, Yattalgoda, Ambepussa, Botale, Wilwatta, Mirigama, Wijaya Rajadahana, Ganegoda, Keenawala, Wadurawa, Veyangoda, Heendeniya Pattiyagoda, Magalegoda, Bemmulla, Daraluwa, Gampaha, Yagoda, Ganemulla, Bulugahagoda, Batuwaththa, Walpola, Ragama, Horape, Enderamulla, Hunupitiya, Wanawasala, Kelaniya, Dematagoda, Maradana, Colombo-Fort', 'Daily', '1st & 2nd Class Reserved');
INSERT INTO `train_schedule` VALUES('0015', 'Udarata Menike', 'Colombo-Fort', '09:45:00', 'Badulla', '19:05:00', 'Colombo-Fort, Maradana, Dematagoda, Kelaniya, Wanawasala, Hunupitiya, Enderamulla, Horape, Ragama, Walpola, Batuwaththa, Bulugahagoda, Ganemulla, Yagoda, Gampaha, Daraluwa, Bemmulla, Magalegoda, Heendeniya Pattiyagoda, Veyangoda, Wadurawa, Keenawala, Ganegoda, Wijaya Rajadahana, Mirigama, Wilwatta, Botale, Ambepussa, Yattalgoda, Bujjomuwa, Alawwa, Walakumbura, Polgahawela, Panaliya, Tismalpola, Yatagama, Rambukkana, Kadigamuwa, Gangoda, Ihala Kotte, Balana, Kadugannawa, Pilimatalawa, Peradeniya, Gampola, Ulapane, Nawalapitiya, Galabodde, Watawala, Rozella, Hatton, Kotagala, Talawakelle, Watagodde, Great Western, Nanu Oya, Ambewela, Pattipola, Ohiya, Idalgashinna, Haputale, Diyatalawe, Bandarawela, Ella, Demodara, Uduwara, Hali Ela, Badulla', 'Daily', 'Observation Saloon 2nd & 3rd Class');
INSERT INTO `train_schedule` VALUES('0016', 'Udarata Menike', 'Badulla', '05:55:00', 'Colombo-Fort', '15:30:00', 'Badulla, Hali Ela, Uduwara, Demodara, Ella, Bandarawela, Diyatalawe, Haputale, Idalgashinna,  Ohiya, Pattipola, Ambewela, Nanu Oya, Great Western, Watagodde, Talawakelle, Kotagala, Hatton, Rozella, Watawala, Galabodde, Nawalapitiya, Ulapane, Gampola, Peradeniya, Pilimatalawa, Kadugannawa, Balana, Ihala Kotte, Gangoda, Kadigamuwa, Rambukkana, Yatagama, Tismalpola, Panaliya, Polgahawela, Walakumbura, Alawwa, Bujjomuwa, Yattalgoda, Ambepussa, Botale, Wilwatta, Mirigama, Wijaya Rajadahana, Ganegoda, Keenawala, Wadurawa, Veyangoda, Heendeniya Pattiyagoda, Magalegoda, Bemmulla, Daraluwa, Gampaha, Yagoda, Ganemulla, Bulugahagoda, Batuwaththa, Walpola, Ragama, Horape, Enderamulla, Hunupitiya, Wanawasala, Kelaniya, Dematagoda, Maradana, Colombo-Fort', 'Daily', 'Observation Saloon 2nd & 3rd Class');
INSERT INTO `train_schedule` VALUES('0019', 'Express', 'Colombo-Fort', '10:30:00', 'Matale', '16:15:00', 'Colombo-Fort, Maradana, Dematagoda, Kelaniya, Wanawasala, Hunupitiya, Enderamulla, Horape, Ragama, Walpola, Batuwaththa, Bulugahagoda, Ganemulla, Yagoda, Gampaha, Daraluwa, Bemmulla, Magalegoda, Heendeniya Pattiyagoda, Veyangoda, Wadurawa, Keenawala, Ganegoda, Wijaya Rajadahana, Mirigama, Wilwatta, Botale, Ambepussa, Yattalgoda, Bujjomuwa, Alawwa, Walakumbura, Polgahawela, Panaliya, Tismalpola, Yatagama, Rambukkana, Kadigamuwa, Gangoda, Ihala Kotte, Balana, Kadugannawa, Pilimatalawa, Peradeniya, Sarasavi Uyana, Kandy, Matale', 'Daily', '2nd & 3rd Class');
INSERT INTO `train_schedule` VALUES('0020', 'Express', 'Kandy', '15:40:00', 'Colombo-Fort', '18:55:00', 'Kandy, Sarasavi Uyana, Peradeniya, Pilimatalawa, Kadugannawa, Balana, Ihala Kotte, Gangoda, Kadigamuwa, Rambukkana, Yatagama, Tismalpola, Panaliya, Polgahawela, Walakumbura, Alawwa, Bujjomuwa, Yattalgoda, Ambepussa, Botale, Wilwatta, Mirigama, Wijaya Rajadahana, Ganegoda, Keenawala, Wadurawa, Veyangoda, Heendeniya Pattiyagoda, Magalegoda, Bemmulla, Daraluwa, Gampaha, Yagoda, Ganemulla, Bulugahagoda, Batuwaththa, Walpola, Ragama, Horape, Enderamulla, Hunupitiya, Wanawasala, Kelaniya, Dematagoda, Maradana, Colombo-Fort', 'Daily', '2nd & 3rd Class');
INSERT INTO `train_schedule` VALUES('0023', 'Express', 'Colombo-Fort', '12:40:00', 'Hatton', '20:00:00', 'Colombo-Fort, Maradana, Dematagoda, Kelaniya, Wanawasala, Hunupitiya, Enderamulla, Horape, Ragama, Walpola, Batuwaththa, Bulugahagoda, Ganemulla, Yagoda, Gampaha, Daraluwa, Bemmulla, Magalegoda, Heendeniya Pattiyagoda, Veyangoda, Wadurawa, Keenawala, Ganegoda, Wijaya Rajadahana, Mirigama, Wilwatta, Botale, Ambepussa, Yattalgoda, Bujjomuwa, Alawwa, Walakumbura, Polgahawela, Panaliya, Tismalpola, Yatagama, Rambukkana, Kadigamuwa, Gangoda, Ihala Kotte, Balana, Kadugannawa, Pilimatalawa, Peradeniya, Gampola, Ulapane, Nawalapitiya, Galabodde, Watawala, Rozella, Hatton', 'Daily', '2nd & 3rd Class');
INSERT INTO `train_schedule` VALUES('0029', 'Intercity Express', 'Colombo-Fort', '15:35:00', 'Kandy', '18:05:00', 'Colombo-Fort, Maradana, Dematagoda, Kelaniya, Wanawasala, Hunupitiya, Enderamulla, Horape, Ragama, Walpola, Batuwaththa, Bulugahagoda, Ganemulla, Yagoda, Gampaha, Daraluwa, Bemmulla, Magalegoda, Heendeniya Pattiyagoda, Veyangoda, Wadurawa, Keenawala, Ganegoda, Wijaya Rajadahana, Mirigama, Wilwatta, Botale, Ambepussa, Yattalgoda, Bujjomuwa, Alawwa, Walakumbura, Polgahawela, Panaliya, Tismalpola, Yatagama, Rambukkana, Kadigamuwa, Gangoda, Ihala Kotte, Balana, Kadugannawa, Pilimatalawa, Peradeniya, Sarasavi Uyana, Kandy', 'Daily', '1st & 2nd Class Stops at Peradeniya');
INSERT INTO `train_schedule` VALUES('0030', 'Intercity Express', 'Kandy', '06:25:00', 'Colombo-Fort', '09:00:00', 'Kandy, Sarasavi Uyana, Peradeniya, Pilimatalawa, Kadugannawa, Balana, Ihala Kotte, Gangoda, Kadigamuwa, Rambukkana, Yatagama, Tismalpola, Panaliya, Polgahawela, Walakumbura, Alawwa, Bujjomuwa, Yattalgoda, Ambepussa, Botale, Wilwatta, Mirigama, Wijaya Rajadahana, Ganegoda, Keenawala, Wadurawa, Veyangoda, Heendeniya Pattiyagoda, Magalegoda, Bemmulla, Daraluwa, Gampaha, Yagoda, Ganemulla, Bulugahagoda, Batuwaththa, Walpola, Ragama, Horape, Enderamulla, Hunupitiya, Wanawasala, Kelaniya, Dematagoda, Maradana, Colombo-Fort', 'Daily', 'Observation & 2nd Class Reserved');
INSERT INTO `train_schedule` VALUES('0035', 'Express', 'Colombo-Fort', '16:55:00', 'Kandy', '20:00:00', 'Colombo-Fort, Maradana, Dematagoda, Kelaniya, Wanawasala, Hunupitiya, Enderamulla, Horape, Ragama, Walpola, Batuwaththa, Bulugahagoda, Ganemulla, Yagoda, Gampaha, Daraluwa, Bemmulla, Magalegoda, Heendeniya Pattiyagoda, Veyangoda, Wadurawa, Keenawala, Ganegoda, Wijaya Rajadahana, Mirigama, Wilwatta, Botale, Ambepussa, Yattalgoda, Bujjomuwa, Alawwa, Walakumbura, Polgahawela, Panaliya, Tismalpola, Yatagama, Rambukkana, Kadigamuwa, Gangoda, Ihala Kotte, Balana, Kadugannawa, Pilimatalawa, Peradeniya, Sarasavi Uyana, Kandy', 'Daily', '2nd & 3rd Class');
INSERT INTO `train_schedule` VALUES('0036', 'Express', 'Matale', '05:15:00', 'Colombo-Fort', '10:10:00', 'Matale, Kandy, Sarasavi Uyana, Peradeniya, Pilimatalawa, Kadugannawa, Balana, Ihala Kotte, Gangoda, Kadigamuwa, Rambukkana, Yatagama, Tismalpola, Panaliya, Polgahawela, Walakumbura, Alawwa, Bujjomuwa, Yattalgoda, Ambepussa, Botale, Wilwatta, Mirigama, Wijaya Rajadahana, Ganegoda, Keenawala, Wadurawa, Veyangoda, Heendeniya Pattiyagoda, Magalegoda, Bemmulla, Daraluwa, Gampaha, Yagoda, Ganemulla, Bulugahagoda, Batuwaththa, Walpola, Ragama, Horape, Enderamulla, Hunupitiya, Wanawasala, Kelaniya, Dematagoda, Maradana, Colombo-Fort', 'Daily', '2nd & 3rd Class');
INSERT INTO `train_schedule` VALUES('0045', 'Night Mail', 'Colombo-Fort', '19:40:00', 'Badulla', '06:30:00', 'Colombo-Fort, Maradana, Dematagoda, Kelaniya, Wanawasala, Hunupitiya, Enderamulla, Horape, Ragama, Walpola, Batuwaththa, Bulugahagoda, Ganemulla, Yagoda, Gampaha, Daraluwa, Bemmulla, Magalegoda, Heendeniya Pattiyagoda, Veyangoda, Wadurawa, Keenawala, Ganegoda, Wijaya Rajadahana, Mirigama, Wilwatta, Botale, Ambepussa, Yattalgoda, Bujjomuwa, Alawwa, Walakumbura, Polgahawela, Panaliya, Tismalpola, Yatagama, Rambukkana, Kadigamuwa, Gangoda, Ihala Kotte, Balana, Kadugannawa, Pilimatalawa, Peradeniya, Gampola, Ulapane, Nawalapitiya, Galabodde, Watawala, Rozella, Hatton, Kotagala, Talawakelle, Watagodde, Great Western, Nanu Oya, Ambewela, Pattipola, Ohiya, Idalgashinna, Haputale, Diyatalawe, Bandarawela, Ella, Demodara, Uduwara, Hali Ela, Badulla', 'Daily', '2nd & 3rd Class');
INSERT INTO `train_schedule` VALUES('0047', 'Night Mail', 'Colombo-Fort', '22:00:00', 'Badulla', '08:45:00', 'Colombo-Fort, Maradana, Dematagoda, Kelaniya, Wanawasala, Hunupitiya, Enderamulla, Horape, Ragama, Walpola, Batuwaththa, Bulugahagoda, Ganemulla, Yagoda, Gampaha, Daraluwa, Bemmulla, Magalegoda, Heendeniya Pattiyagoda, Veyangoda, Wadurawa, Keenawala, Ganegoda, Wijaya Rajadahana, Mirigama, Wilwatta, Botale, Ambepussa, Yattalgoda, Bujjomuwa, Alawwa, Walakumbura, Polgahawela, Panaliya, Tismalpola, Yatagama, Rambukkana, Kadigamuwa, Gangoda, Ihala Kotte, Balana, Kadugannawa, Pilimatalawa, Peradeniya, Gampola, Ulapane, Nawalapitiya, Galabodde, Watawala, Rozella, Hatton, Kotagala, Talawakelle, Watagodde, Great Western, Nanu Oya, Ambewela, Pattipola, Ohiya, Idalgashinna, Haputale, Diyatalawe, Bandarawela, Ella, Demodara, Uduwara, Hali Ela, Badulla', 'Daily', '1st Class Berths and 2nd and 3rd Class Sleeperettes');
INSERT INTO `train_schedule` VALUES('0048', 'Night Mail', 'Badulla', '19:50:00', 'Colombo-Fort', '05:50:00', 'Badulla, Hali Ela, Uduwara, Demodara, Ella, Bandarawela, Diyatalawe, Haputale, Idalgashinna,  Ohiya, Pattipola, Ambewela, Nanu Oya, Great Western, Watagodde, Talawakelle, Kotagala, Hatton, Rozella, Watawala, Galabodde, Nawalapitiya, Ulapane, Gampola, Peradeniya, Pilimatalawa, Kadugannawa, Balana, Ihala Kotte, Gangoda, Kadigamuwa, Rambukkana, Yatagama, Tismalpola, Panaliya, Polgahawela, Walakumbura, Alawwa, Bujjomuwa, Yattalgoda, Ambepussa, Botale, Wilwatta, Mirigama, Wijaya Rajadahana, Ganegoda, Keenawala, Wadurawa, Veyangoda, Heendeniya Pattiyagoda, Magalegoda, Bemmulla, Daraluwa, Gampaha, Yagoda, Ganemulla, Bulugahagoda, Batuwaththa, Walpola, Ragama, Horape, Enderamulla, Hunupitiya, Wanawasala, Kelaniya, Dematagoda, Maradana, Colombo-Fort', 'Daily', '2nd & 3rd Class Sleeperettes');
INSERT INTO `train_schedule` VALUES('0050', 'Night Mail', 'Matara', '18:30:00', 'Trincomalee', '08:45:00', 'Matara, Kamburugamuva, Weligama, Ahangama, Koggala, Talpe, Galle, Hikkaduwa, Ambalangoda, Balapitiya, Kosgoda, Bentota, Aluthgama, Beruwala, Kaluthara, Wadduwa, Panadura, Moratuwa, Ratmalana, Mount Lavinia, Dehiwala, Wellawatta, Bambalapitiya, Kollutipiya, Slave Island, Colombo-Fort, Maradana, Maradana, Dematagoda, Kelaniya, Wanawasala, Hunupitiya, Enderamulla, Horape, Ragama, Walpola, Batuwaththa, Bulugahagoda, Ganemulla, Yagoda, Gampaha, Daraluwa, Bemmulla, Magalegoda, Heendeniya Pattiyagoda, Veyangoda, Wadurawa, Keenawala, Ganegoda, Wijaya Rajadahana, Mirigama, Wilwatta, Botale, Ambepussa, Yattalgoda, Bujjomuwa, Alawwa, Walakumbura, Polgahawela, Polgahawela, Potuhera, Kurunegala, Wellawa, Ganewatta, Maho, Moragollagama, Kalawewa, Kekirawa, Habarana, Gal Oya, Kanthalai, Thampalakamam, China Bay, Trincomalee', 'Daily', 'Departure Via Colombo-Fort at 22:30 2nd and 3rd Class');
INSERT INTO `train_schedule` VALUES('0051', 'Night Mail', 'Trincomalee', '17:00:00', 'Matara', '07:15:00', 'Trincomalee, China Bay, Thampalakamam, Kanthalai, Gal Oya, Habarana, Kekirawa, Kalawewa, Moragollagama, Maho, Ganewatta, Wellawa, Kurunegala, Potuhera, Polgahawela, Polgahawela, Walakumbura, Alawwa, Bujjomuwa, Yattalgoda, Ambepussa, Botale, Wilwatta, Mirigama, Wijaya Rajadahana, Ganegoda, Keenawala, Wadurawa, Veyangoda, Heendeniya Pattiyagoda, Magalegoda, Bemmulla, Daraluwa, Gampaha, Yagoda, Ganemulla, Bulugahagoda, Batuwaththa, Walpola, Ragama, Horape, Enderamulla, Hunupitiya, Wanawasala, Kelaniya, Dematagoda, Maradana, Colombo-Fort, Slave Island, Kollutipiya, Bambalapitiya, Wellawatta, Dehiwala, Mount Lavinia, Ratmalana, Moratuwa, Panadura, Wadduwa, Kaluthara, Beruwala, Aluthgama, Bentota, Kosgoda, Balapitiya, Ambalangoda, Hikkaduwa, Galle, Talpe, Koggala,\r\nAhangama, Weligama, Kamburugamuva, Matara', 'Daily', 'Departure Via Colombo-Fort at 3:15 2nd & 3rd Class');
INSERT INTO `train_schedule` VALUES('0056', 'Gaalu Kumari', 'Maradana', '13:40:00', 'Matara', '18:40:00', 'Maradana, Colombo-Fort, Slave Island, Kollutipiya, Bambalapitiya, Wellawatta, Dehiwala, Mount Lavinia, Ratmalana, Moratuwa, Panadura, Wadduwa, Kaluthara, Beruwala, Aluthgama, Bentota, Kosgoda, Balapitiya, Ambalangoda, Hikkaduwa, Galle, Talpe, Koggala,\r\nAhangama, Weligama, Kamburugamuva, Matara', 'Monday to Friday', '2nd & 3rd Class Colombo-Fort 14:05 Galle 18:16 Sat, Sun, Poya 3rd Class');
INSERT INTO `train_schedule` VALUES('0057', 'Gaalu Kumari', 'Matara', '07:25:00', 'Maradana', '11:50:00', 'Matara, Kamburugamuva, Weligama, Ahangama, Koggala, Talpe, Galle, Hikkaduwa, Ambalangoda, Balapitiya, Kosgoda, Bentota, Aluthgama, Beruwala, Kaluthara, Wadduwa, Panadura, Moratuwa, Ratmalana, Mount Lavinia, Dehiwala, Wellawatta, Bambalapitiya, Kollutipiya, Slave Island, Colombo-Fort, Maradana', 'Daily', '2nd & 3rd Class');
INSERT INTO `train_schedule` VALUES('0058', 'Ruhunu Kumari', 'Maradana', '15:50:00', 'Matara', '19:30:00', 'Maradana, Colombo-Fort, Slave Island, Kollutipiya, Bambalapitiya, Wellawatta, Dehiwala, Mount Lavinia, Ratmalana, Moratuwa, Panadura, Wadduwa, Kaluthara, Beruwala, Aluthgama, Bentota, Kosgoda, Balapitiya, Ambalangoda, Hikkaduwa, Galle, Talpe, Koggala,\r\nAhangama, Weligama, Kamburugamuva, Matara', 'Daily', '2nd & 3rd Class');
INSERT INTO `train_schedule` VALUES('0059', 'Ruhunu Kumari', 'Matara', '05:40:00', 'Maradana', '09:20:00', 'Matara, Kamburugamuva, Weligama, Ahangama, Koggala, Talpe, Galle, Hikkaduwa, Ambalangoda, Balapitiya, Kosgoda, Bentota, Aluthgama, Beruwala, Kaluthara, Wadduwa, Panadura, Moratuwa, Ratmalana, Mount Lavinia, Dehiwala, Wellawatta, Bambalapitiya, Kollutipiya, Slave Island, Colombo-Fort, Maradana', 'Daily', '2nd & 3rd Class');
INSERT INTO `train_schedule` VALUES('0077', 'Yaldevi', 'Colombo-Fort', '05:45:00', 'Vavuniya', '11:50:00', 'Colombo-Fort, Maradana, Dematagoda, Kelaniya, Wanawasala, Hunupitiya, Enderamulla, Horape, Ragama, Walpola, Batuwaththa, Bulugahagoda, Ganemulla, Yagoda, Gampaha, Daraluwa, Bemmulla, Magalegoda, Heendeniya Pattiyagoda, Veyangoda, Wadurawa, Keenawala, Ganegoda, Wijaya Rajadahana, Mirigama, Wilwatta, Botale, Ambepussa, Yattalgoda, Bujjomuwa, Alawwa, Walakumbura, Polgahawela, Potuhera, Kurunegala, Wellawa, Ganewatta, Maho, Galgamuwa, Talawa, Anuradhapura, Medawachchiya, Vavuniya', 'Daily', 'Travels via Anuradhapura Air Conditioned 1st Class 2nd & 3 Class');
INSERT INTO `train_schedule` VALUES('0078', 'Yaldevi', 'Vavuniya', '13:15:00', 'Colombo-Fort', '19:20:00', 'Vavuniya, Medawachchiya, Anuradhapura, Talawa, Galgamuwa, Maho, Ganewatta, Wellawa, Kurunegala, Potuhera, Polgahawela, Walakumbura, Alawwa, Bujjomuwa, Yattalgoda, Ambepussa, Botale, Wilwatta, Mirigama, Wijaya Rajadahana, Ganegoda, Keenawala, Wadurawa, Veyangoda, Heendeniya Pattiyagoda, Magalegoda, Bemmulla, Daraluwa, Gampaha, Yagoda, Ganemulla, Bulugahagoda, Batuwaththa, Walpola, Ragama, Horape, Enderamulla, Hunupitiya, Wanawasala, Kelaniya, Dematagoda, Maradana, Colombo-Fort', 'Daily', '2nd & 3rd Class Reserved/Non');
INSERT INTO `train_schedule` VALUES('0081', 'Express', 'Colombo-Fort', '06:15:00', 'Trincomalee', '14:10:00', 'Colombo-Fort, Maradana, Dematagoda, Kelaniya, Wanawasala, Hunupitiya, Enderamulla, Horape, Ragama, Walpola, Batuwaththa, Bulugahagoda, Ganemulla, Yagoda, Gampaha, Daraluwa, Bemmulla, Magalegoda, Heendeniya Pattiyagoda, Veyangoda, Wadurawa, Keenawala, Ganegoda, Wijaya Rajadahana, Mirigama, Wilwatta, Botale, Ambepussa, Yattalgoda, Bujjomuwa, Alawwa, Walakumbura, Polgahawela, Polgahawela, Potuhera, Kurunegala, Wellawa, Ganewatta, Maho, Moragollagama, Kalawewa, Kekirawa, Habarana, Gal Oya, Kanthalai, Thampalakamam, China Bay, Trincomalee', 'Daily', '2nd & 3rd Class Connection to Gal Oya - Polonnaruwa at 13:15');
INSERT INTO `train_schedule` VALUES('0082', 'Express', 'Trincomalee', '09:45:00', 'Colombo-Fort', '17:45:00', 'Trincomalee, China Bay, Thampalakamam, Kanthalai, Gal Oya, Gal Oya, Habarana, Kekirawa, Kalawewa, Moragollagama, Maho, Ganewatta, Wellawa, Kurunegala, Potuhera, Polgahawela, Walakumbura, Alawwa, Bujjomuwa, Yattalgoda, Ambepussa, Botale, Wilwatta, Mirigama, Wijaya Rajadahana, Ganegoda, Keenawala, Wadurawa, Veyangoda, Heendeniya Pattiyagoda, Magalegoda, Bemmulla, Daraluwa, Gampaha, Yagoda, Ganemulla, Bulugahagoda, Batuwaththa, Walpola, Ragama, Horape, Enderamulla, Hunupitiya, Wanawasala, Kelaniya, Dematagoda, Maradana, Colombo-Fort', 'Daily', '2nd & 3rd Class Connection to Gal Oya-Polonnaruwa at 10:50');
INSERT INTO `train_schedule` VALUES('0085', 'Rajarata Rajini', 'Matara', '09:15:00', 'Vavuniya', '20:25:00', 'Matara, Kamburugamuva, Weligama, Ahangama, Koggala, Talpe, Galle, Hikkaduwa, Ambalangoda, Balapitiya, Kosgoda, Bentota, Aluthgama, Beruwala, Kaluthara, Wadduwa, Panadura, Moratuwa, Ratmalana, Mount Lavinia, Dehiwala, Wellawatta, Bambalapitiya, Kollutipiya, Slave Island, Colombo-Fort, Maradana, Dematagoda, Kelaniya, Wanawasala, Hunupitiya, Enderamulla, Horape, Ragama, Walpola, Batuwaththa, Bulugahagoda, Ganemulla, Yagoda, Gampaha, Daraluwa, Bemmulla, Magalegoda, Heendeniya Pattiyagoda, Veyangoda, Wadurawa, Keenawala, Ganegoda, Wijaya Rajadahana, Mirigama, Wilwatta, Botale, Ambepussa, Yattalgoda, Bujjomuwa, Alawwa, Walakumbura, Polgahawela, Potuhera, Kurunegala, Wellawa, Ganewatta, Maho, Galgamuwa, Talawa, Anuradhapura, Medawachchiya, Vavuniya', 'Daily', '2nd & 3rd Class Via Colombo-Fort Departure at 14:00');
INSERT INTO `train_schedule` VALUES('0086', 'Rajarata Rajini', 'Vavuniya', '03:15:00', 'Matara', '14:15:00', 'Vavuniya, Medawachchiya, Anuradhapura, Talawa, Galgamuwa, Maho, Ganewatta, Wellawa, Kurunegala, Potuhera, Polgahawela, Walakumbura, Alawwa, Bujjomuwa, Yattalgoda, Ambepussa, Botale, Wilwatta, Mirigama, Wijaya Rajadahana, Ganegoda, Keenawala, Wadurawa, Veyangoda, Heendeniya Pattiyagoda, Magalegoda, Bemmulla, Daraluwa, Gampaha, Yagoda, Ganemulla, Bulugahagoda, Batuwaththa, Walpola, Ragama, Horape, Enderamulla, Hunupitiya, Wanawasala, Kelaniya, Dematagoda, Maradana, Colombo-Fort, Slave Island, Kollutipiya, Bambalapitiya, Wellawatta, Dehiwala, Mount Lavinia, Ratmalana, Moratuwa, Panadura, Wadduwa, Kaluthara, Beruwala, Aluthgama, Bentota, Kosgoda, Balapitiya, Ambalangoda, Hikkaduwa, Galle, Talpe, Koggala, Ahangama, Weligama, Kamburugamuva, Matara', 'Daily', '2nd & 3rd Class Via Colombo-Fort Departure at 10:30');
INSERT INTO `train_schedule` VALUES('0089', 'Night Mail', 'Colombo-Fort', '21:30:00', 'Vavuniya', '04:25:00', 'Colombo-Fort, Maradana, Dematagoda, Kelaniya, Wanawasala, Hunupitiya, Enderamulla, Horape, Ragama, Walpola, Batuwaththa, Bulugahagoda, Ganemulla, Yagoda, Gampaha, Daraluwa, Bemmulla, Magalegoda, Heendeniya Pattiyagoda, Veyangoda, Wadurawa, Keenawala, Ganegoda, Wijaya Rajadahana, Mirigama, Wilwatta, Botale, Ambepussa, Yattalgoda, Bujjomuwa, Alawwa, Walakumbura, Polgahawela, Potuhera, Kurunegala, Wellawa, Ganewatta, Maho, Galgamuwa, Talawa, Anuradhapura, Medawachchiya, Vavuniya', 'Daily', '2nd & 3rd Class Via Anuradhapura at 2:45');
INSERT INTO `train_schedule` VALUES('0090', 'Night Mail', 'Vavuniya', '21:30:00', 'Colombo-Fort', '04:50:00', 'Vavuniya, Medawachchiya, Anuradhapura, Talawa, Galgamuwa, Maho, Ganewatta, Wellawa, Kurunegala, Potuhera, Polgahawela, Walakumbura, Alawwa, Bujjomuwa, Yattalgoda, Ambepussa, Botale, Wilwatta, Mirigama, Wijaya Rajadahana, Ganegoda, Keenawala, Wadurawa, Veyangoda, Heendeniya Pattiyagoda, Magalegoda, Bemmulla, Daraluwa, Gampaha, Yagoda, Ganemulla, Bulugahagoda, Batuwaththa, Walpola, Ragama, Horape, Enderamulla, Hunupitiya, Wanawasala, Kelaniya, Dematagoda, Maradana, Colombo-Fort', 'Daily', '2nd & 3rd Class Via Anuradhapura at 23:10');
INSERT INTO `train_schedule` VALUES('0094', 'Intercity Train/Express', 'Colombo-Fort', '16:45:00', 'Galle', '19:15:00', 'Colombo-Fort, Slave Island, Kollutipiya, Bambalapitiya, Wellawatta, Dehiwala, Mount Lavinia, Ratmalana, Moratuwa, Panadura, Wadduwa, Kaluthara, Beruwala, Aluthgama, Bentota, Kosgoda, Balapitiya, Ambalangoda, Hikkaduwa, Galle', 'Daily', '2nd & 3rd Class Via Hikkaduwa at 18:52');
INSERT INTO `train_schedule` VALUES('0095', 'Intercity Train/Express', 'Galle', '07:40:00', 'Colombo-Fort', '10:00:00', 'Galle, Hikkaduwa, Ambalangoda, Balapitiya, Kosgoda, Bentota, Aluthgama, Beruwala, Kaluthara, Wadduwa, Panadura, Moratuwa, Ratmalana, Mount Lavinia, Dehiwala, Wellawatta, Bambalapitiya, Kollutipiya, Slave Island, Colombo-Fort', 'Daily', '2nd & 3rd Class Via Hikkaduwa at 8:05');
INSERT INTO `train_schedule` VALUES('0096', 'Express Train', 'Colombo-Fort', '15:55:00', 'Vavuniya', '20:40:00', 'Colombo-Fort, Maradana, Dematagoda, Kelaniya, Wanawasala, Hunupitiya, Enderamulla, Horape, Ragama, Walpola, Batuwaththa, Bulugahagoda, Ganemulla, Yagoda, Gampaha, Daraluwa, Bemmulla, Magalegoda, Heendeniya Pattiyagoda, Veyangoda, Wadurawa, Keenawala, Ganegoda, Wijaya Rajadahana, Mirigama, Wilwatta, Botale, Ambepussa, Yattalgoda, Bujjomuwa, Alawwa, Walakumbura, Polgahawela, Potuhera, Kurunegala, Wellawa, Ganewatta, Maho, Galgamuwa, Talawa, Anuradhapura, Medawachchiya, Vavuniya', 'Daily', 'A/C and 2nd Class Via Anuradhapura at 19:40');
INSERT INTO `train_schedule` VALUES('0097', 'Express Train', 'Vavuniya', '05:45:00', 'Colombo-Fort', '10:25:00', 'Vavuniya, Medawachchiya, Anuradhapura, Talawa, Galgamuwa, Maho, Ganewatta, Wellawa, Kurunegala, Potuhera, Polgahawela, Walakumbura, Alawwa, Bujjomuwa, Yattalgoda, Ambepussa, Botale, Wilwatta, Mirigama, Wijaya Rajadahana, Ganegoda, Keenawala, Wadurawa, Veyangoda, Heendeniya Pattiyagoda, Magalegoda, Bemmulla, Daraluwa, Gampaha, Yagoda, Ganemulla, Bulugahagoda, Batuwaththa, Walpola, Ragama, Horape, Enderamulla, Hunupitiya, Wanawasala, Kelaniya, Dematagoda, Maradana, Colombo-Fort', 'Daily', 'A/C and 2nd Class Via Anuradhapura at 6:40');
INSERT INTO `train_schedule` VALUES('1006', 'Long Distance', 'Badulla', '08:50:00', 'Colombo-Fort', '19:30:00', 'Badulla, Hali Ela, Uduwara, Demodara, Ella, Bandarawela, Diyatalawe, Haputale, Idalgashinna,  Ohiya, Pattipola, Ambewela, Nanu Oya, Great Western, Watagodde, Talawakelle, Kotagala, Hatton, Rozella, Watawala, Galabodde, Nawalapitiya, Ulapane, Gampola, Peradeniya, Pilimatalawa, Kadugannawa, Balana, Ihala Kotte, Gangoda, Kadigamuwa, Rambukkana, Yatagama, Tismalpola, Panaliya, Polgahawela, Walakumbura, Alawwa, Bujjomuwa, Yattalgoda, Ambepussa, Botale, Wilwatta, Mirigama, Wijaya Rajadahana, Ganegoda, Keenawala, Wadurawa, Veyangoda, Heendeniya Pattiyagoda, Magalegoda, Bemmulla, Daraluwa, Gampaha, Yagoda, Ganemulla, Bulugahagoda, Batuwaththa, Walpola, Ragama, Horape, Enderamulla, Hunupitiya, Wanawasala, Kelaniya, Dematagoda, Maradana, Colombo-Fort', 'Daily', 'Train Starting from Badulla');
INSERT INTO `train_schedule` VALUES('1016', 'Long Distance', 'Badulla', '05:45:00', 'Colombo-Fort', '15:40:00', 'Badulla, Hali Ela, Uduwara, Demodara, Ella, Bandarawela, Diyatalawe, Haputale, Idalgashinna,  Ohiya, Pattipola, Ambewela, Nanu Oya, Great Western, Watagodde, Talawakelle, Kotagala, Hatton, Rozella, Watawala, Galabodde, Nawalapitiya, Ulapane, Gampola, Peradeniya, Pilimatalawa, Kadugannawa, Balana, Ihala Kotte, Gangoda, Kadigamuwa, Rambukkana, Yatagama, Tismalpola, Panaliya, Polgahawela, Walakumbura, Alawwa, Bujjomuwa, Yattalgoda, Ambepussa, Botale, Wilwatta, Mirigama, Wijaya Rajadahana, Ganegoda, Keenawala, Wadurawa, Veyangoda, Heendeniya Pattiyagoda, Magalegoda, Bemmulla, Daraluwa, Gampaha, Yagoda, Ganemulla, Bulugahagoda, Batuwaththa, Walpola, Ragama, Horape, Enderamulla, Hunupitiya, Wanawasala, Kelaniya, Dematagoda, Maradana, Colombo-Fort', 'Daily', 'Train Starting from Badulla');
INSERT INTO `train_schedule` VALUES('1017', 'Long Distance', 'Bandarawela', '07:18:00', 'Colombo-Fort', '15:40:00', 'Bandarawela, Diyatalawe, Haputale, Idalgashinna,  Ohiya, Pattipola, Ambewela, Nanu Oya, Great Western, Watagodde, Talawakelle, Kotagala, Hatton, Rozella, Watawala, Galabodde, Nawalapitiya, Ulapane, Gampola, Peradeniya, Pilimatalawa, Kadugannawa, Balana, Ihala Kotte, Gangoda, Kadigamuwa, Rambukkana, Yatagama, Tismalpola, Panaliya, Polgahawela, Walakumbura, Alawwa, Bujjomuwa, Yattalgoda, Ambepussa, Botale, Wilwatta, Mirigama, Wijaya Rajadahana, Ganegoda, Keenawala, Wadurawa, Veyangoda, Heendeniya Pattiyagoda, Magalegoda, Bemmulla, Daraluwa, Gampaha, Yagoda, Ganemulla, Bulugahagoda, Batuwaththa, Walpola, Ragama, Horape, Enderamulla, Hunupitiya, Wanawasala, Kelaniya, Dematagoda, Maradana, Colombo-Fort', 'Daily', 'Train Starting from Badulla');
INSERT INTO `train_schedule` VALUES('1046', 'Long Distance', 'Badulla', '18:00:00', 'Colombo-Fort', '05:15:00', 'Badulla, Hali Ela, Uduwara, Demodara, Ella, Bandarawela, Diyatalawe, Haputale, Idalgashinna,  Ohiya, Pattipola, Ambewela, Nanu Oya, Great Western, Watagodde, Talawakelle, Kotagala, Hatton, Rozella, Watawala, Galabodde, Nawalapitiya, Ulapane, Gampola, Peradeniya, Pilimatalawa, Kadugannawa, Balana, Ihala Kotte, Gangoda, Kadigamuwa, Rambukkana, Yatagama, Tismalpola, Panaliya, Polgahawela, Walakumbura, Alawwa, Bujjomuwa, Yattalgoda, Ambepussa, Botale, Wilwatta, Mirigama, Wijaya Rajadahana, Ganegoda, Keenawala, Wadurawa, Veyangoda, Heendeniya Pattiyagoda, Magalegoda, Bemmulla, Daraluwa, Gampaha, Yagoda, Ganemulla, Bulugahagoda, Batuwaththa, Walpola, Ragama, Horape, Enderamulla, Hunupitiya, Wanawasala, Kelaniya, Dematagoda, Maradana, Colombo-Fort', 'Daily', 'Train Starting from Badulla');
INSERT INTO `train_schedule` VALUES('4002', 'Long Distance', 'Anuradhapura', '16:55:00', 'Colombo-Fort', '20:30:00', 'Anuradhapura, Talawa, Galgamuwa, Maho, Ganewatta, Wellawa, Kurunegala, Potuhera, Polgahawela, Walakumbura, Alawwa, Bujjomuwa, Yattalgoda, Ambepussa, Botale, Wilwatta, Mirigama, Wijaya Rajadahana, Ganegoda, Keenawala, Wadurawa, Veyangoda, Heendeniya Pattiyagoda, Magalegoda, Bemmulla, Daraluwa, Gampaha, Yagoda, Ganemulla, Bulugahagoda, Batuwaththa, Walpola, Ragama, Horape, Enderamulla, Hunupitiya, Wanawasala, Kelaniya, Dematagoda, Maradana, Colombo-Fort', 'Daily', 'Train Starting from Thandikulam');
INSERT INTO `train_schedule` VALUES('4004', 'Long Distance', 'Anuradhapura', '06:40:00', 'Colombo-Fort', '10:25:00', 'Anuradhapura, Talawa, Galgamuwa, Maho, Ganewatta, Wellawa, Kurunegala, Potuhera, Polgahawela, Walakumbura, Alawwa, Bujjomuwa, Yattalgoda, Ambepussa, Botale, Wilwatta, Mirigama, Wijaya Rajadahana, Ganegoda, Keenawala, Wadurawa, Veyangoda, Heendeniya Pattiyagoda, Magalegoda, Bemmulla, Daraluwa, Gampaha, Yagoda, Ganemulla, Bulugahagoda, Batuwaththa, Walpola, Ragama, Horape, Enderamulla, Hunupitiya, Wanawasala, Kelaniya, Dematagoda, Maradana, Colombo-Fort', 'Daily', 'Train Starting from Vavuniya');
INSERT INTO `train_schedule` VALUES('4086', 'Long Distance', 'Anuradhapura', '05:00:00', 'Colombo-Fort', '09:55:00', 'Anuradhapura, Talawa, Galgamuwa, Maho, Ganewatta, Wellawa, Kurunegala, Potuhera, Polgahawela, Walakumbura, Alawwa, Bujjomuwa, Yattalgoda, Ambepussa, Botale, Wilwatta, Mirigama, Wijaya Rajadahana, Ganegoda, Keenawala, Wadurawa, Veyangoda, Heendeniya Pattiyagoda, Magalegoda, Bemmulla, Daraluwa, Gampaha, Yagoda, Ganemulla, Bulugahagoda, Batuwaththa, Walpola, Ragama, Horape, Enderamulla, Hunupitiya, Wanawasala, Kelaniya, Dematagoda, Maradana, Colombo-Fort', 'Daily', 'Train Starting from Vavuniya');
INSERT INTO `train_schedule` VALUES('4090', 'Long Distance', 'Anuradhapura', '23:30:00', 'Colombo-Fort', '04:35:00', 'Anuradhapura, Talawa, Galgamuwa, Maho, Ganewatta, Wellawa, Kurunegala, Potuhera, Polgahawela, Walakumbura, Alawwa, Bujjomuwa, Yattalgoda, Ambepussa, Botale, Wilwatta, Mirigama, Wijaya Rajadahana, Ganegoda, Keenawala, Wadurawa, Veyangoda, Heendeniya Pattiyagoda, Magalegoda, Bemmulla, Daraluwa, Gampaha, Yagoda, Ganemulla, Bulugahagoda, Batuwaththa, Walpola, Ragama, Horape, Enderamulla, Hunupitiya, Wanawasala, Kelaniya, Dematagoda, Maradana, Colombo-Fort', 'Daily', 'Train Starting from Thandikulam');
INSERT INTO `train_schedule` VALUES('8040', 'Long Distance', 'Colombo-Fort', '08:35:00', 'Aluthgama', '09:58:00', 'Colombo-Fort, Slave Island, Kollutipiya, Bambalapitiya, Wellawatta, Dehiwala, Mount Lavinia, Ratmalana, Moratuwa, Panadura, Wadduwa, Kaluthara, Beruwala, Aluthgama', 'Daily', 'Train Starting from Colombo-Fort Train Runs to Matara');
INSERT INTO `train_schedule` VALUES('8041', 'Long Distance', 'Colombo-Fort', '08:35:00', 'Galle', '11:18:00', 'Colombo-Fort, Slave Island, Kollutipiya, Bambalapitiya, Wellawatta, Dehiwala, Mount Lavinia, Ratmalana, Moratuwa, Panadura, Wadduwa, Kaluthara, Beruwala, Aluthgama, Bentota, Kosgoda, Balapitiya, Ambalangoda, Hikkaduwa, Galle', 'Daily', 'Train Starting from Colombo-Fort Train Runs to Matara');
INSERT INTO `train_schedule` VALUES('8050', 'Long Distance', 'Colombo-Fort', '06:55:00', 'Aluthgama', '08:34:00', 'Colombo-Fort, Slave Island, Kollutipiya, Bambalapitiya, Wellawatta, Dehiwala, Mount Lavinia, Ratmalana, Moratuwa, Panadura, Wadduwa, Kaluthara, Beruwala, Aluthgama', 'Daily', 'Train Starting from Maradana Train Runs to Matara');
INSERT INTO `train_schedule` VALUES('8051', 'Long Distance', 'Colombo-Fort', '06:55:00', 'Galle', '09:48:00', 'Colombo-Fort, Slave Island, Kollutipiya, Bambalapitiya, Wellawatta, Dehiwala, Mount Lavinia, Ratmalana, Moratuwa, Panadura, Wadduwa, Kaluthara, Beruwala, Aluthgama, Bentota, Kosgoda, Balapitiya, Ambalangoda, Hikkaduwa, Galle', 'Daily', 'Train Starting from Maradana Train Runs to Matara');
INSERT INTO `train_schedule` VALUES('8056', 'Long Distance', 'Colombo-Fort', '14:05:00', 'Aluthgama', '15:29:00', 'Colombo-Fort, Slave Island, Kollutipiya, Bambalapitiya, Wellawatta, Dehiwala, Mount Lavinia, Ratmalana, Moratuwa, Panadura, Wadduwa, Kaluthara, Beruwala, Aluthgama', 'Daily', 'Train Starting from Maradana Train Runs to Matara');
INSERT INTO `train_schedule` VALUES('8058', 'Long Distance', 'Colombo-Fort', '15:50:00', 'Aluthgama', '17:03:00', 'Colombo-Fort, Slave Island, Kollutipiya, Bambalapitiya, Wellawatta, Dehiwala, Mount Lavinia, Ratmalana, Moratuwa, Panadura, Wadduwa, Kaluthara, Beruwala, Aluthgama', 'Daily', 'Train Starting from Maradana, Train Runs to Matara');
INSERT INTO `train_schedule` VALUES('8086', 'Long Distance', 'Colombo-Fort', '10:30:00', 'Aluthgama', '11:54:00', 'Colombo-Fort, Slave Island, Kollutipiya, Bambalapitiya, Wellawatta, Dehiwala, Mount Lavinia, Ratmalana, Moratuwa, Panadura, Wadduwa, Kaluthara, Beruwala, Aluthgama', 'Daily', 'Train Starting from Colombo-Fort Train Runs to Matara');
INSERT INTO `train_schedule` VALUES('8096', 'Long Distance', 'Colombo-Fort', '16:46:00', 'Aluthgama', '18:07:00', 'Colombo-Fort, Slave Island, Kollutipiya, Bambalapitiya, Wellawatta, Dehiwala, Mount Lavinia, Ratmalana, Moratuwa, Panadura, Wadduwa, Kaluthara, Beruwala, Aluthgama', 'Monday to Friday', 'Train Starting from Maradana Train Runs to Matara');
INSERT INTO `train_schedule` VALUES('8097', 'Colombo Commuter', 'Colombo-Fort', '17:55:00', 'Aluthgama', '19:47:00', 'Colombo-Fort, Slave Island, Kollutipiya, Bambalapitiya, Wellawatta, Dehiwala, Mount Lavinia, Ratmalana, Moratuwa, Panadura, Wadduwa, Kaluthara, Beruwala, Aluthgama', 'Saturday and Sunday', 'Train Starting from Maradana Train Runs to Galle');
INSERT INTO `train_schedule` VALUES('8742', 'Colombo Commuter', 'Colombo-Fort', '11:15:00', 'Aluthgama', '13:07:00', 'Colombo-Fort, Slave Island, Kollutipiya, Bambalapitiya, Wellawatta, Dehiwala, Mount Lavinia, Ratmalana, Moratuwa, Panadura, Wadduwa, Kaluthara, Beruwala, Aluthgama', 'Daily', 'Train Starting from Colombo-Fort Train Runs to Aluthgama');
INSERT INTO `train_schedule` VALUES('8751', 'Colombo Commuter', 'Colombo-Fort', '14:10:00', 'Aluthgama', '16:13:00', 'Colombo-Fort, Slave Island, Kollutipiya, Bambalapitiya, Wellawatta, Dehiwala, Mount Lavinia, Ratmalana, Moratuwa, Panadura, Wadduwa, Kaluthara, Beruwala, Aluthgama', 'Daily', 'Train Starting from Maradana Train Runs to Aluthgama');
