(function(){function g(a){throw a;}var i=true,k=null,l=false,aa=navigator,ba=Error,ca=Boolean,m=undefined,da=encodeURIComponent,ea=parseInt,fa=parseFloat,n=String,p=window,ga=Number,q=Object,t=document,ha=decodeURIComponent,ia=RegExp,ja=Array,u=Math;function ka(a,b){return a.toString=b}function la(a,b){return a.length=b}function ma(a,b){return a.className=b}function na(a,b){return a.width=b}function oa(a,b){return a.cancel=b}function pa(a,b){return a.innerHTML=b}function qa(a,b){return a.value=b}
function ra(a,b){return a.currentTarget=b}function sa(a,b){return a.left=b}function ta(a,b){return a.target=b}function ua(a,b){return a.send=b}function va(a,b){return a.isAvailable=b}function wa(a,b){return a.bottom=b}function xa(a,b){return a.restore=b}function ya(a,b){return a.display=b}function za(a,b){return a.isSupported=b}function Aa(a,b){return a.height=b}function Ba(a,b){return a.right=b}
var w="appendChild",Ca="scrollTop",x="push",z="toString",A="length",Da="propertyIsEnumerable",Ea="getBoundingClientRect",Fa="plugins",B="prototype",Ga="test",Ha="shift",Ia="className",Ja="exec",Ka="clearTimeout",D="width",La="index",Ma="text",Na="clientWidth",Oa="cancel",Pa="round",Qa="abort",Ra="slice",Sa="setTimeout",E="replace",F="nodeType",Ta="document",Ua="split",Va="offsetWidth",Wa="concat",Xa="createTextNode",Ya="value",Za="location",$a="item",ab="insertBefore",G="indexOf",bb="message",cb=
"hasOwnProperty",H="dispatchEvent",I="style",db="close",eb="nodeName",fb="currentTarget",J="body",K="left",gb="write",hb="ownerDocument",ib="removeChild",jb="target",kb="screenX",lb="screenY",mb="lastChild",L="call",nb="match",ob="getBoxObjectFor",pb="send",qb="createElement",rb="keyCode",M="firstChild",sb="forEach",tb="isAvailable",ub="clientHeight",vb="scrollLeft",wb="clientLeft",xb="bottom",yb="currentStyle",zb="href",Ab="substring",Bb="clientTop",Cb="handleEvent",Db="restore",Eb="type",Fb="apply",
Gb="translate",Hb="parentWindow",N="tagName",Ib="setPosition",Jb="reset",Kb="defaultView",Lb="name",O="parentNode",Mb="fileName",Nb="isSupported",Ob="nextSibling",Pb="contentWindow",P="height",Qb="offsetHeight",Rb="join",Sb="getElementsByTagName",Tb="nodeValue",Ub="documentElement",Vb="substr",Wb="right";function Xb(a){return function(b){this[a]=b}}function Yb(a){return function(){return this[a]}}var Q,Zb=Zb||{},R=this;
function $b(a,b,c){a=a[Ua](".");c=c||R;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a[A]&&(d=a[Ha]());)if(!a[A]&&b!==m)c[d]=b;else c=c[d]?c[d]:c[d]={}}function ac(a,b){for(var c=a[Ua]("."),d=b||R,e;e=c[Ha]();)if(d[e])d=d[e];else return k;return d}function bc(){}function cc(a){a.Bc=function(){return a.Hd||(a.Hd=new a)}}
function dc(a){var b=typeof a;if(b=="object")if(a){if(a instanceof ja||!(a instanceof q)&&q[B][z][L](a)=="[object Array]"||typeof a[A]=="number"&&typeof a.splice!="undefined"&&typeof a[Da]!="undefined"&&!a[Da]("splice"))return"array";if(!(a instanceof q)&&(q[B][z][L](a)=="[object Function]"||typeof a[L]!="undefined"&&typeof a[Da]!="undefined"&&!a[Da]("call")))return"function"}else return"null";else if(b=="function"&&typeof a[L]=="undefined")return"object";return b}
function ec(a){return dc(a)=="array"}function fc(a){var b=dc(a);return b=="array"||b=="object"&&typeof a[A]=="number"}function gc(a){return typeof a=="string"}function hc(a){return dc(a)=="function"}function ic(a){a=dc(a);return a=="object"||a=="array"||a=="function"}function jc(a){return a[kc]||(a[kc]=++lc)}var kc="closure_uid_"+u.floor(u.random()*2147483648)[z](36),lc=0;
function T(a,b){var c=b||R;if(arguments[A]>2){var d=ja[B][Ra][L](arguments,2);return function(){var e=ja[B][Ra][L](arguments);ja[B].unshift[Fb](e,d);return a[Fb](c,e)}}else return function(){return a[Fb](c,arguments)}}function mc(a){var b=ja[B][Ra][L](arguments,1);return function(){var c=ja[B][Ra][L](arguments);c.unshift[Fb](c,b);return a[Fb](this,c)}}var nc=Date.now||function(){return+new Date};function U(a,b){function c(){}c.prototype=b[B];a.s=b[B];a.prototype=new c;a[B].constructor=a};var oc=google[Gb]._const,pc=oc._cl||"en",qc=oc._cuc,rc=oc._cnad||l,sc=oc._cnal||{},tc=oc._cam=="lib"?1:0,uc;a:{for(var vc=t[Sb]("meta"),wc=0;wc<vc[A];++wc)if(vc[wc][Lb]=="google-translate-customization"){uc=vc[wc].content;break a}uc=""}
var xc=uc,yc=(oc._cac||"te")+(tc==1?"_lib":""),zc=oc._pah||"",Ac=oc._pbi||"",Bc=oc._pci||"",Cc=oc._phf||"",Dc=oc._plla||"",Ec=oc._pli||"",Fc=oc._pmi||"",Gc=oc._ps||"",Hc=oc._puh||"",Ic=p[Za].protocol=="https:"?"https://":"http://",Jc=Ic+"www.google.com/images/cleardot.gif",Kc=Ic+"www.google.com/intl/"+pc[E]("_","-")+"/images/logos/translate_logo_sm.png",Lc="http://"+Hc+"/translate_suggestion";function Mc(){}Mc[B].oc=l;Mc[B].p=function(){if(!this.oc){this.oc=i;this.r()}};Mc[B].r=function(){};function Nc(a){return a[E](/^[\s\xa0]+|[\s\xa0]+$/g,"")}function Oc(a){return a[E](/^[\s\xa0]+/,"")}function Pc(a){return a[E](/[\s\xa0]+$/,"")}var Qc=/^[a-zA-Z0-9\-_.!~*'()]*$/;function Rc(a){a=n(a);if(!Qc[Ga](a))return da(a);return a}
function Sc(a,b){if(b)return a[E](Tc,"&amp;")[E](Uc,"&lt;")[E](Vc,"&gt;")[E](Wc,"&quot;");else{if(!Xc[Ga](a))return a;if(a[G]("&")!=-1)a=a[E](Tc,"&amp;");if(a[G]("<")!=-1)a=a[E](Uc,"&lt;");if(a[G](">")!=-1)a=a[E](Vc,"&gt;");if(a[G]('"')!=-1)a=a[E](Wc,"&quot;");return a}}var Tc=/&/g,Uc=/</g,Vc=/>/g,Wc=/\"/g,Xc=/[&<>\"]/;
function Yc(a){if(a[G]("&")!=-1){if("document"in R&&a[G]("<")==-1){a=a;var b=R[Ta][qb]("div");pa(b,"<pre>"+a+"</pre>");b[M].normalize&&b[M].normalize();a=b[M][M][Tb];pa(b,"");a=a[E](/(\r\n|\r|\n)/g,"\n")}else a=Zc(a);return a}return a}function Zc(a){return a[E](/&([^;]+);/g,function(b,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if(c.charAt(0)=="#"){var d=ga("0"+c[Vb](1));if(!isNaN(d))return n.fromCharCode(d)}return b}})}
function $c(a,b){for(var c=0,d=Nc(n(a))[Ua]("."),e=Nc(n(b))[Ua]("."),f=u.max(d[A],e[A]),h=0;c==0&&h<f;h++){var j=d[h]||"",o=e[h]||"",r=ia("(\\d*)(\\D*)","g"),y=ia("(\\d*)(\\D*)","g");do{var s=r[Ja](j)||["","",""],v=y[Ja](o)||["","",""];if(s[0][A]==0&&v[0][A]==0)break;c=s[1][A]==0?0:ea(s[1],10);var Z=v[1][A]==0?0:ea(v[1],10);c=ad(c,Z)||ad(s[2][A]==0,v[2][A]==0)||ad(s[2],v[2])}while(c==0)}return c}function ad(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var bd=ja[B],cd=bd[G]?function(a,b,c){return bd[G][L](a,b,c)}:function(a,b,c){c=c==k?0:c<0?u.max(0,a[A]+c):c;if(gc(a)){if(!gc(b)||b[A]!=1)return-1;return a[G](b,c)}for(c=c;c<a[A];c++)if(c in a&&a[c]===b)return c;return-1},dd=bd[sb]?function(a,b,c){bd[sb][L](a,b,c)}:function(a,b,c){for(var d=a[A],e=gc(a)?a[Ua](""):a,f=0;f<d;f++)f in e&&b[L](c,e[f],f,a)};function ed(a,b){return cd(a,b)>=0}function fd(a,b){var c=cd(a,b),d;if(d=c>=0){var e=a;c=c;bd.splice[L](e,c,1)}return d}
function gd(){return bd[Wa][Fb](bd,arguments)}function hd(a){if(ec(a))return gd(a);else{for(var b=[],c=0,d=a[A];c<d;c++)b[c]=a[c];return b}}function id(a){for(var b=1;b<arguments[A];b++){var c=arguments[b],d;if(ec(c)||(d=fc(c))&&c[cb]("callee"))a[x][Fb](a,c);else if(d)for(var e=a[A],f=c[A],h=0;h<f;h++)a[e+h]=c[h];else a[x](c)}}function jd(a){return bd.splice[Fb](a,kd(arguments,1))}function kd(a,b,c){return arguments[A]<=2?bd[Ra][L](a,b):bd[Ra][L](a,b,c)};function ld(a,b){this.x=a!==m?a:0;this.y=b!==m?b:0}ld[B].Q=function(){return new ld(this.x,this.y)};function md(a,b){return new ld(a.x-b.x,a.y-b.y)};function nd(a,b){na(this,a);Aa(this,b)}nd[B].Q=function(){return new nd(this[D],this[P])};nd[B].floor=function(){na(this,u.floor(this[D]));Aa(this,u.floor(this[P]));return this};nd[B].round=function(){na(this,u[Pa](this[D]));Aa(this,u[Pa](this[P]));return this};function od(a,b,c){for(var d in a)b[L](c,a[d],d,a)}function qd(a){var b=[],c=0;for(var d in a)b[c++]=a[d];return b}function rd(a){var b=[],c=0;for(var d in a)b[c++]=d;return b}function sd(a,b){var c;if(c=b in a)delete a[b];return c}var td=["constructor","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","toLocaleString","toString","valueOf"];
function ud(a){for(var b,c,d=1;d<arguments[A];d++){c=arguments[d];for(b in c)a[b]=c[b];for(var e=0;e<td[A];e++){b=td[e];if(q[B][cb][L](c,b))a[b]=c[b]}}};var vd,wd,xd,yd,zd,Ad,Bd;function Cd(){return R.navigator?R.navigator.userAgent:k}function Dd(){return R.navigator}zd=yd=xd=wd=vd=l;var Ed;if(Ed=Cd()){var Fd=Dd();vd=Ed[G]("Opera")==0;wd=!vd&&Ed[G]("MSIE")!=-1;yd=(xd=!vd&&Ed[G]("WebKit")!=-1)&&Ed[G]("Mobile")!=-1;zd=!vd&&!xd&&Fd.product=="Gecko"}var Gd=vd,V=wd,Hd=zd,Id=xd,Jd=yd,Kd,Ld=Dd(),Md=Kd=Ld&&Ld.platform||"";Ad=Md[G]("Mac")!=-1;Md[G]("Win");Md[G]("Linux");Bd=!!Dd()&&(Dd().appVersion||"")[G]("X11")!=-1;var Nd=Ad,Od=Bd,Pd;
a:{var Qd="",Rd;if(Gd&&R.opera){var Sd=R.opera.version;Qd=typeof Sd=="function"?Sd():Sd}else{if(Hd)Rd=/rv\:([^\);]+)(\)|;)/;else if(V)Rd=/MSIE\s+([^\);]+)(\)|;)/;else if(Id)Rd=/WebKit\/(\S+)/;if(Rd){var Td=Rd[Ja](Cd());Qd=Td?Td[1]:""}}if(V){var Ud,Vd=R[Ta];Ud=Vd?Vd.documentMode:m;if(Ud>fa(Qd)){Pd=n(Ud);break a}}Pd=Qd}var Wd=Pd,Xd={};function Yd(a){return Xd[a]||(Xd[a]=$c(Wd,a)>=0)};var Zd,$d=!V||Yd("9"),ae=V&&!Yd("9");function be(a){return(a=a[Ia])&&typeof a[Ua]=="function"?a[Ua](/\s+/):[]}function ce(a){var b=be(a),c=kd(arguments,1),d;d=b;c=c;for(var e=0,f=0;f<c[A];f++)if(!ed(d,c[f])){d[x](c[f]);e++}d=e==c[A];ma(a,b[Rb](" "));return d}function de(a){var b=be(a),c=kd(arguments,1),d;d=b;c=c;for(var e=0,f=0;f<d[A];f++)if(ed(c,d[f])){jd(d,f--,1);e++}d=e==c[A];ma(a,b[Rb](" "));return d};function ee(a){return a?new fe(ge(a)):Zd||(Zd=new fe)}
function he(a,b,c,d){a=d||a;b=b&&b!="*"?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(!Id||ie(t)||Yd("528"))&&(b||c)){c=b+(c?"."+c:"");return a.querySelectorAll(c)}if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,h;h=a[f];f++)if(b==h[eb])d[e++]=h;la(d,e);return d}else return a}a=a[Sb](b||"*");if(c){d={};for(f=e=0;h=a[f];f++){b=h[Ia];if(typeof b[Ua]=="function"&&ed(b[Ua](/\s+/),c))d[e++]=h}la(d,e);return d}else return a}
function je(a,b){od(b,function(c,d){if(d=="style")a[I].cssText=c;else if(d=="class")ma(a,c);else if(d=="for")a.htmlFor=c;else if(d in ke)a.setAttribute(ke[d],c);else a[d]=c})}var ke={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",type:"type"};
function le(a){var b=a[Ta];if(Id&&!Yd("500")&&!Jd){if(typeof a.innerHeight=="undefined")a=p;b=a.innerHeight;var c=a[Ta][Ub].scrollHeight;if(a==a.top)if(c<b)b-=15;return new nd(a.innerWidth,b)}a=ie(b);if(Gd&&!Yd("9.50"))a=l;a=a?b[Ub]:b[J];return new nd(a[Na],a[ub])}function me(a){a=!Id&&ie(a)?a[Ub]:a[J];return new ld(a[vb],a[Ca])}function ne(){return oe(t,arguments)}
function oe(a,b){var c=b[0],d=b[1];if(!$d&&d&&(d[Lb]||d[Eb])){c=["<",c];d[Lb]&&c[x](' name="',Sc(d[Lb]),'"');if(d[Eb]){c[x](' type="',Sc(d[Eb]),'"');var e={};ud(e,d);d=e;delete d[Eb]}c[x](">");c=c[Rb]("")}c=a[qb](c);if(d)if(gc(d))ma(c,d);else ec(d)?ce[Fb](k,[c][Wa](d)):je(c,d);b[A]>2&&pe(a,c,b,2);return c}function pe(a,b,c,d){function e(h){if(h)b[w](gc(h)?a[Xa](h):h)}for(d=d;d<c[A];d++){var f=c[d];fc(f)&&!(ic(f)&&f[F]>0)?dd(qe(f)?hd(f):f,e):e(f)}}function ie(a){return a.compatMode=="CSS1Compat"}
function re(a,b){a[w](b)}function se(a){pe(ge(a),a,arguments,1)}function te(a){for(var b;b=a[M];)a[ib](b)}function ue(a,b){b[O]&&b[O][ab](a,b)}function ve(a){return a&&a[O]?a[O][ib](a):k}function we(a,b){var c=b[O];c&&c.replaceChild(a,b)}function xe(a,b){if(a.contains&&b[F]==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||ca(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b[O];return b==a}function ge(a){return a[F]==9?a:a[hb]||a[Ta]}
function ye(a){return a=Id?a[Ta]||a[Pb][Ta]:a.contentDocument||a[Pb][Ta]}function ze(a,b){if("textContent"in a)a.textContent=b;else if(a[M]&&a[M][F]==3){for(;a[mb]!=a[M];)a[ib](a[mb]);a[M].data=b}else{te(a);var c=ge(a);a[w](c[Xa](b))}}var Ae={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},Be={IMG:" ",BR:"\n"};
function Ce(a){if(ae&&"innerText"in a)a=a.innerText[E](/(\r\n|\r|\n)/g,"\n");else{var b=[];De(a,b,i);a=b[Rb]("")}a=a[E](/ \xAD /g," ")[E](/\xAD/g,"");V||(a=a[E](/ +/g," "));if(a!=" ")a=a[E](/^\s*/,"");return a}function De(a,b,c){if(!(a[eb]in Ae))if(a[F]==3)c?b[x](n(a[Tb])[E](/(\r\n|\r|\n)/g,"")):b[x](a[Tb]);else if(a[eb]in Be)b[x](Be[a[eb]]);else for(a=a[M];a;){De(a,b,c);a=a[Ob]}}
function qe(a){if(a&&typeof a[A]=="number")if(ic(a))return typeof a[$a]=="function"||typeof a[$a]=="string";else if(hc(a))return typeof a[$a]=="function";return l}function fe(a){this.a=a||R[Ta]||t}function Ee(a){return a.a}Q=fe[B];Q.n=function(a){return gc(a)?this.a.getElementById(a):a};Q.Wc=fe[B].n;Q.t=function(){return oe(this.a,arguments)};Q.createElement=function(a){return this.a[qb](a)};Q.createTextNode=function(a){return this.a[Xa](a)};function Fe(a){return ie(a.a)}
function Ge(a){return me(a.a)}Q.appendChild=re;Q.G=se;Q.gc=te;Q.removeNode=ve;Q.contains=xe;Q.Hb=ze;var He;!V||Yd("9");V&&Yd("8");function Ie(a,b){this.type=a;ta(this,b);ra(this,this[jb])}U(Ie,Mc);Ie[B].r=function(){delete this[Eb];delete this[jb];delete this[fb]};Ie[B].a=l;Ie[B].b=i;function Je(a,b){a&&Ke(this,a,b)}U(Je,Ie);Q=Je[B];ta(Q,k);Q.relatedTarget=k;Q.offsetX=0;Q.offsetY=0;Q.clientX=0;Q.clientY=0;Q.screenX=0;Q.screenY=0;Q.button=0;Q.keyCode=0;Q.charCode=0;Q.ctrlKey=l;Q.altKey=l;Q.shiftKey=l;Q.metaKey=l;Q.Pd=l;Q.wc=k;
function Ke(a,b,c){var d=a.type=b[Eb];ta(a,b[jb]||b.srcElement);ra(a,c);if(c=b.relatedTarget){if(Hd)try{c=c[eb]&&c}catch(e){c=k}}else if(d=="mouseover")c=b.fromElement;else if(d=="mouseout")c=b.toElement;a.relatedTarget=c;a.offsetX=b.offsetX!==m?b.offsetX:b.layerX;a.offsetY=b.offsetY!==m?b.offsetY:b.layerY;a.clientX=b.clientX!==m?b.clientX:b.pageX;a.clientY=b.clientY!==m?b.clientY:b.pageY;a.screenX=b[kb]||0;a.screenY=b[lb]||0;a.button=b.button;a.keyCode=b[rb]||0;a.charCode=b.charCode||(d=="keypress"?
b[rb]:0);a.ctrlKey=b.ctrlKey;a.altKey=b.altKey;a.shiftKey=b.shiftKey;a.metaKey=b.metaKey;a.Pd=Nd?b.metaKey:b.ctrlKey;a.wc=b;delete a.b;delete a.a}Q.r=function(){Je.s.r[L](this);this.wc=k;ta(this,k);ra(this,k);this.relatedTarget=k};function Le(a,b){this.d=b;this.b=[];var c=a;if(c>this.d)g(ba("[goog.structs.SimplePool] Initial cannot be greater than max"));for(var d=0;d<c;d++)this.b[x](this.a?this.a():{})}U(Le,Mc);Le[B].a=k;Le[B].c=k;function Me(a){if(a.b[A])return a.b.pop();return a.a?a.a():{}}function Ne(a,b){a.b[A]<a.d?a.b[x](b):Oe(a,b)}function Oe(a,b){if(a.c)a.c(b);else if(ic(b))if(hc(b.p))b.p();else for(var c in b)delete b[c]}Le[B].r=function(){Le.s.r[L](this);for(var a=this.b;a[A];)Oe(this,a.pop());delete this.b};var Pe,Qe,Re="ScriptEngine"in R;Qe=(Pe=Re&&R.ScriptEngine()=="JScript")?R.ScriptEngineMajorVersion()+"."+R.ScriptEngineMinorVersion()+"."+R.ScriptEngineBuildVersion():"0";var Se=Pe,Te=Qe;function Ue(){}var Ve=0;Ue[B].ha=0;Ue[B].$a=l;Ue[B].a=l;Ue[B].handleEvent=function(a){if(this.b)return this.Wa[L](this.Bb||this.src,a);return this.Wa[Cb][L](this.Wa,a)};var We,Xe,Ye,Ze,$e,af,bf,cf,df,ef,ff;
(function(){function a(){return{o:0,da:0}}function b(){return[]}function c(){function v(Z){return h[L](v.src,v.ha,Z)}return v}function d(){return new Ue}function e(){return new Je}var f=Se&&!($c(Te,"5.7")>=0),h;af=function(v){h=v};if(f){We=function(){return Me(j)};Xe=function(v){Ne(j,v)};Ye=function(){return Me(o)};Ze=function(v){Ne(o,v)};$e=function(){return Me(r)};bf=function(){Ne(r,c())};cf=function(){return Me(y)};df=function(v){Ne(y,v)};ef=function(){return Me(s)};ff=function(v){Ne(s,v)};var j=
new Le(0,600);j.a=a;var o=new Le(0,600);o.a=b;var r=new Le(0,600);r.a=c;var y=new Le(0,600);y.a=d;var s=new Le(0,600);s.a=e}else{We=a;Xe=bc;Ye=b;Ze=bc;$e=c;bf=bc;cf=d;df=bc;ef=e;ff=bc}})();var gf={},hf={},jf={},kf="on",lf={};
function mf(a,b,c,d,e){if(b)if(ec(b)){for(var f=0;f<b[A];f++)mf(a,b[f],c,d,e);return k}else{d=!!d;var h=hf;b in h||(h[b]=We());h=h[b];if(!(d in h)){h[d]=We();h.o++}h=h[d];var j=jc(a),o;h.da++;if(h[j]){o=h[j];for(f=0;f<o[A];f++){h=o[f];if(h.Wa==c&&h.Bb==e){if(h.$a)break;return o[f].ha}}}else{o=h[j]=Ye();h.o++}f=$e();f.src=a;var r=h=cf();c=c;var y=f,s=a,v=b,Z=d;e=e;if(hc(c))r.b=i;else if(c&&c[Cb]&&hc(c[Cb]))r.b=l;else g(ba("Invalid listener argument"));r.Wa=c;r.c=y;r.src=s;r.type=v;r.fb=!!Z;r.Bb=e;
r.a=l;r.ha=++Ve;r.$a=l;e=h.ha;f.ha=e;o[x](h);gf[e]=h;jf[j]||(jf[j]=Ye());jf[j][x](h);if(a.addEventListener){if(a==R||!a.sc)a.addEventListener(b,f,d)}else a.attachEvent(nf(b),f);return e}else g(ba("Invalid event type"))}function of(a,b,c,d,e){if(ec(b)){for(var f=0;f<b[A];f++)of(a,b[f],c,d,e);return k}d=!!d;a=pf(a,b,d);if(!a)return l;for(f=0;f<a[A];f++)if(a[f].Wa==c&&a[f].fb==d&&a[f].Bb==e)return qf(a[f].ha);return l}
function qf(a){if(!gf[a])return l;var b=gf[a];if(b.$a)return l;var c=b.src,d=b[Eb],e=b.c,f=b.fb;if(c.removeEventListener){if(c==R||!c.sc)c.removeEventListener(d,e,f)}else c.detachEvent&&c.detachEvent(nf(d),e);c=jc(c);e=hf[d][f][c];if(jf[c]){var h=jf[c];fd(h,b);h[A]==0&&delete jf[c]}b.$a=i;e.Jc=i;rf(d,f,c,e);delete gf[a];return i}
function rf(a,b,c,d){if(!d.Db)if(d.Jc){for(var e=0,f=0;e<d[A];e++)if(d[e].$a){var h=d[e].c;h.src=k;bf(h);df(d[e])}else{if(e!=f)d[f]=d[e];f++}la(d,f);d.Jc=l;if(f==0){Ze(d);delete hf[a][b][c];hf[a][b].o--;if(hf[a][b].o==0){Xe(hf[a][b]);delete hf[a][b];hf[a].o--}if(hf[a].o==0){Xe(hf[a]);delete hf[a]}}}}
function sf(a,b,c){var d=0,e=a==k,f=b==k,h=c==k;c=!!c;if(e)od(jf,function(o){for(var r=o[A]-1;r>=0;r--){var y=o[r];if((f||b==y[Eb])&&(h||c==y.fb)){qf(y.ha);d++}}});else{a=jc(a);if(jf[a]){a=jf[a];for(e=a[A]-1;e>=0;e--){var j=a[e];if((f||b==j[Eb])&&(h||c==j.fb)){qf(j.ha);d++}}}}return d}function pf(a,b,c){var d=hf;if(b in d){d=d[b];if(c in d){d=d[c];a=jc(a);if(d[a])return d[a]}}return k}function nf(a){if(a in lf)return lf[a];return lf[a]=kf+a}
function tf(a,b,c,d,e){var f=1;b=jc(b);if(a[b]){a.da--;a=a[b];if(a.Db)a.Db++;else a.Db=1;try{for(var h=a[A],j=0;j<h;j++){var o=a[j];if(o&&!o.$a)f&=uf(o,e)!==l}}finally{a.Db--;rf(c,d,b,a)}}return ca(f)}function uf(a,b){var c=a[Cb](b);a.a&&qf(a.ha);return c}
function vf(a,b){if(!gf[a])return i;var c=gf[a],d=c[Eb],e=hf;if(!(d in e))return i;e=e[d];var f,h,j;if(He===m)He=V&&!R.addEventListener;if(j=He){f=b||ac("window.event");j=i in e;var o=l in e;if(j){if(f[rb]<0||f.returnValue!=m)return i;a:{var r=f,y=l;if(r[rb]==0)try{r.keyCode=-1;break a}catch(s){y=i}if(y||r.returnValue==m)r.returnValue=i}}r=ef();Ke(r,f,this);f=i;try{if(j){for(var v=Ye(),Z=r[fb];Z;Z=Z[O])v[x](Z);h=e[i];h.da=h.o;for(var S=v[A]-1;!r.a&&S>=0&&h.da;S--){ra(r,v[S]);f&=tf(h,v[S],d,i,r)}if(o){h=
e[l];h.da=h.o;for(S=0;!r.a&&S<v[A]&&h.da;S++){ra(r,v[S]);f&=tf(h,v[S],d,l,r)}}}else f=uf(c,r)}finally{if(v){la(v,0);Ze(v)}r.p();ff(r)}return f}d=new Je(b,this);try{f=uf(c,d)}finally{d.p()}return f}af(vf);function wf(a,b,c,d){this.top=a;Ba(this,b);wa(this,c);sa(this,d)}wf[B].Q=function(){return new wf(this.top,this[Wb],this[xb],this[K])};wf[B].contains=function(a){a=!this||!a?l:a instanceof wf?a[K]>=this[K]&&a[Wb]<=this[Wb]&&a.top>=this.top&&a[xb]<=this[xb]:a.x>=this[K]&&a.x<=this[Wb]&&a.y>=this.top&&a.y<=this[xb];return a};function xf(a,b,c,d){sa(this,a);this.top=b;na(this,c);Aa(this,d)}xf[B].Q=function(){return new xf(this[K],this.top,this[D],this[P])};xf[B].contains=function(a){return a instanceof xf?this[K]<=a[K]&&this[K]+this[D]>=a[K]+a[D]&&this.top<=a.top&&this.top+this[P]>=a.top+a[P]:a.x>=this[K]&&a.x<=this[K]+this[D]&&a.y>=this.top&&a.y<=this.top+this[P]};function yf(a,b,c){gc(b)?zf(a,c,b):od(b,mc(zf,a))}function zf(a,b,c){a[I][Af(c)]=b}function Bf(a,b){var c=ge(a);if(c[Kb]&&c[Kb].getComputedStyle)if(c=c[Kb].getComputedStyle(a,""))return c[b];return k}function Cf(a,b){return Bf(a,b)||(a[yb]?a[yb][b]:k)||a[I][b]}function Df(a,b,c){var d,e=Hd&&(Nd||Od)&&Yd("1.9");if(b instanceof ld){d=b.x;b=b.y}else{d=b;b=c}sa(a[I],Ef(d,e));a[I].top=Ef(b,e)}function Ff(a){var b=a[Ea]();if(V){a=a[hb];b.left-=a[Ub][wb]+a[J][wb];b.top-=a[Ub][Bb]+a[J][Bb]}return b}
function Gf(a){if(V)return a.offsetParent;var b=ge(a),c=Cf(a,"position"),d=c=="fixed"||c=="absolute";for(a=a[O];a&&a!=b;a=a[O]){c=Cf(a,"position");d=d&&c=="static"&&a!=b[Ub]&&a!=b[J];if(!d&&(a.scrollWidth>a[Na]||a.scrollHeight>a[ub]||c=="fixed"||c=="absolute"))return a}return k}
function Hf(a){var b=new wf(0,Infinity,Infinity,0),c=ee(a),d=c.a[J],e=!Id&&ie(c.a)?c.a[Ub]:c.a[J],f;for(a=a;a=Gf(a);)if((!V||a[Na]!=0)&&(!Id||a[ub]!=0||a!=d)&&(a.scrollWidth!=a[Na]||a.scrollHeight!=a[ub])&&Cf(a,"overflow")!="visible"){var h=If(a),j;j=a;if(Hd&&!Yd("1.9")){var o=fa(Bf(j,"borderLeftWidth"));if(Jf(j)){var r=j[Va]-j[Na]-o-fa(Bf(j,"borderRightWidth"));o+=r}j=new ld(o,fa(Bf(j,"borderTopWidth")))}else j=new ld(j[wb],j[Bb]);h.x+=j.x;h.y+=j.y;b.top=u.max(b.top,h.y);Ba(b,u.min(b[Wb],h.x+a[Na]));
wa(b,u.min(b[xb],h.y+a[ub]));sa(b,u.max(b[K],h.x));f=f||a!=e}d=e[vb];e=e[Ca];if(Id){b.left+=d;b.top+=e}else{sa(b,u.max(b[K],d));b.top=u.max(b.top,e)}if(!f||Id){b.right+=d;b.bottom+=e}c=le(c.a[Hb]||c.a[Kb]||p);Ba(b,u.min(b[Wb],d+c[D]));wa(b,u.min(b[xb],e+c[P]));return b.top>=0&&b[K]>=0&&b[xb]>b.top&&b[Wb]>b[K]?b:k}
function If(a){var b,c=ge(a),d=Cf(a,"position"),e=Hd&&c[ob]&&!a[Ea]&&d=="absolute"&&(b=c[ob](a))&&(b[kb]<0||b[lb]<0),f=new ld(0,0),h;b=c?c[F]==9?c:ge(c):t;h=V&&!Fe(ee(b))?b[J]:b[Ub];if(a==h)return f;if(a[Ea]){b=Ff(a);a=Ge(ee(c));f.x=b[K]+a.x;f.y=b.top+a.y}else if(c[ob]&&!e){b=c[ob](a);a=c[ob](h);f.x=b[kb]-a[kb];f.y=b[lb]-a[lb]}else{b=a;do{f.x+=b.offsetLeft;f.y+=b.offsetTop;if(b!=a){f.x+=b[wb]||0;f.y+=b[Bb]||0}if(Id&&Cf(b,"position")=="fixed"){f.x+=c[J][vb];f.y+=c[J][Ca];break}b=b.offsetParent}while(b&&
b!=a);if(Gd||Id&&d=="absolute")f.y-=c[J].offsetTop;for(b=a;(b=Gf(b))&&b!=c[J]&&b!=h;){f.x-=b[vb];if(!Gd||b[N]!="TR")f.y-=b[Ca]}}return f}function Kf(a,b){var c=new ld(0,0),d=ge(a)?ge(a)[Hb]||ge(a)[Kb]:p,e=a;do{var f;if(d==b)f=If(e);else{var h=e;f=new ld;if(h[F]==1)if(h[Ea]){var j=Ff(h);f.x=j[K];f.y=j.top}else{j=Ge(ee(h));h=If(h);f.x=h.x-j.x;f.y=h.y-j.y}else{f.x=h.clientX;f.y=h.clientY}f=f}f=f;c.x+=f.x;c.y+=f.y}while(d&&d!=b&&(e=d.frameElement)&&(d=d.parent));return c}
function Ef(a,b){if(typeof a=="number")a=(b?u[Pa](a):a)+"px";return a}function Lf(a){var b=Gd&&!Yd("10");if(Cf(a,"display")!="none")return b?new nd(a[Va]||a[Na],a[Qb]||a[ub]):new nd(a[Va],a[Qb]);var c=a[I],d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";ya(c,"inline");if(b){b=a[Va]||a[Na];a=a[Qb]||a[ub]}else{b=a[Va];a=a[Qb]}ya(c,d);c.position=f;c.visibility=e;return new nd(b,a)}function Mf(a){var b=If(a);a=Lf(a);return new xf(b.x,b.y,a[D],a[P])}var Nf={};
function Af(a){return Nf[a]||(Nf[a]=n(a)[E](/\-([a-z])/g,function(b,c){return c.toUpperCase()}))}function W(a,b){ya(a[I],b?"":"none")}function Of(a,b){var c=ee(b),d=k;if(V){d=c.a.createStyleSheet();Pf(d,a)}else{var e=he(c.a,"head",void 0,void 0)[0];if(!e){d=he(c.a,"body",void 0,void 0)[0];e=c.t("head");d[O][ab](e,d)}d=c.t("style");Pf(d,a);c[w](e,d)}return d}function Pf(a,b){if(V)a.cssText=b;else{var c=Id?"innerText":"innerHTML";a[c]=b}}function Jf(a){return"rtl"==Cf(a,"direction")}
function Qf(a){return new nd(a[Va],a[Qb])}
function Rf(a,b){var c=ge(a),d=Fe(ee(c));if(V&&(!d||!Yd("8"))){c=a[I];if(d){c.pixelWidth=b[D];c.pixelHeight=b[P]}else{var e=a,f="padding";if(V){d=Sf(e,f+"Left");var h=Sf(e,f+"Right"),j=Sf(e,f+"Top");e=Sf(e,f+"Bottom");d=new wf(j,h,e,d)}else{d=Bf(e,f+"Left");h=Bf(e,f+"Right");j=Bf(e,f+"Top");e=Bf(e,f+"Bottom");d=new wf(fa(j),fa(h),fa(e),fa(d))}f=a;if(V){h=Tf(f,"borderLeft");j=Tf(f,"borderRight");e=Tf(f,"borderTop");f=Tf(f,"borderBottom");h=new wf(e,j,f,h)}else{h=Bf(f,"borderLeftWidth");j=Bf(f,"borderRightWidth");
e=Bf(f,"borderTopWidth");f=Bf(f,"borderBottomWidth");h=new wf(fa(e),fa(j),fa(f),fa(h))}c.pixelWidth=b[D]+h[K]+d[K]+d[Wb]+h[Wb];c.pixelHeight=b[P]+h.top+d.top+d[xb]+h[xb]}}else{c=b;d="content-box";h=a[I];if(Hd)h.MozBoxSizing=d;else if(Id)h.WebkitBoxSizing=d;else if(Gd&&!Yd("9.50"))d?h.setProperty("box-sizing",d):h.removeProperty("box-sizing");else h.qe=d;na(h,c[D]+"px");Aa(h,c[P]+"px")}}
function Uf(a,b,c,d){if(/^\d+px?$/[Ga](b))return ea(b,10);else{var e=a[I][c],f=a.runtimeStyle[c];a.runtimeStyle[c]=a[yb][c];a[I][c]=b;b=a[I][d];a[I][c]=e;a.runtimeStyle[c]=f;return b}}function Sf(a,b){return Uf(a,a[yb]?a[yb][b]:k,"left","pixelLeft")}var Vf={thin:2,medium:4,thick:6};function Tf(a,b){if((a[yb]?a[yb][b+"Style"]:k)=="none")return 0;var c=a[yb]?a[yb][b+"Width"]:k;if(c in Vf)return Vf[c];return Uf(a,c,"left","pixelLeft")};function Wf(a){this.c=a}U(Wf,Mc);var Xf=new Le(0,100);function X(a,b,c,d,e,f){if(ec(c))for(var h=0;h<c[A];h++)X(a,b,c[h],d,e,f);else{c=mf(b,c,d||a,e||l,f||a.c||a);b=a;c=c;if(b.a)b.a[c]=i;else if(b.b){b.a=Me(Xf);b.a[b.b]=i;b.b=k;b.a[c]=i}else b.b=c}return a}
function Yf(a,b,c,d,e,f){if(a.b||a.a)if(ec(c))for(var h=0;h<c[A];h++)Yf(a,b,c[h],d,e,f);else{a:{d=d||a;f=f||a.c||a;e=!!(e||l);if(b=pf(b,c,e))for(c=0;c<b[A];c++)if(b[c].Wa==d&&b[c].fb==e&&b[c].Bb==f){b=b[c];break a}b=k}if(b){b=b.ha;qf(b);if(a.a)sd(a.a,b);else if(a.b==b)a.b=k}}return a}function Zf(a){if(a.a){for(var b in a.a){qf(b);delete a.a[b]}Ne(Xf,a.a);a.a=k}else a.b&&qf(a.b)}Wf[B].r=function(){Wf.s.r[L](this);Zf(this)};Wf[B].handleEvent=function(){g(ba("EventHandler.handleEvent not implemented"))};function $f(){}U($f,Mc);Q=$f[B];Q.sc=i;Q.Gb=k;Q.jc=Xb("Gb");Q.addEventListener=function(a,b,c,d){mf(this,a,b,c,d)};Q.removeEventListener=function(a,b,c,d){of(this,a,b,c,d)};
Q.dispatchEvent=function(a){a=a;if(gc(a))a=new Ie(a,this);else if(a instanceof Ie)ta(a,a[jb]||this);else{var b=a;a=new Ie(a[Eb],this);ud(a,b)}b=1;var c,d=a[Eb],e=hf;if(d in e){e=e[d];d=i in e;var f;if(d){c=[];for(f=this;f;f=f.Gb)c[x](f);f=e[i];f.da=f.o;for(var h=c[A]-1;!a.a&&h>=0&&f.da;h--){ra(a,c[h]);b&=tf(f,c[h],a[Eb],i,a)&&a.b!=l}}if(f=l in e){f=e[l];f.da=f.o;if(d)for(h=0;!a.a&&h<c[A]&&f.da;h++){ra(a,c[h]);b&=tf(f,c[h],a[Eb],l,a)&&a.b!=l}else for(c=this;!a.a&&c&&f.da;c=c.Gb){ra(a,c);b&=tf(f,c,
a[Eb],l,a)&&a.b!=l}}a=ca(b)}else a=i;return a};Q.r=function(){$f.s.r[L](this);sf(this);this.Gb=k};function ag(){}cc(ag);ag[B].a=0;ag.Bc();function bg(a){this.b=a||ee();this.Wd=cg}U(bg,$f);bg[B].M=ag.Bc();var cg=k;Q=bg[B];Q.R=k;Q.Ba=l;Q.g=k;Q.Wd=k;Q.Md=k;Q.Qa=k;Q.ra=k;Q.vb=k;Q.he=l;Q.n=Yb("g");Q.jc=function(a){if(this.Qa&&this.Qa!=a)g(ba("Method not supported"));bg.s.jc[L](this,a)};Q.t=function(){this.g=this.b[qb]("div")};Q.ma=function(a){dg(this,a)};function dg(a,b,c){if(a.Ba)g(ba("Component already rendered"));a.g||a.t();b?b[ab](a.g,c||k):a.b.a[J][w](a.g);if(!a.Qa||a.Qa.Ba)a.Z()}
Q.Z=function(){this.Ba=i;eg(this,function(a){!a.Ba&&a.n()&&a.Z()})};Q.L=function(){eg(this,function(a){a.Ba&&a.L()});this.D&&Zf(this.D);this.Ba=l};Q.r=function(){bg.s.r[L](this);this.Ba&&this.L();if(this.D){this.D.p();delete this.D}eg(this,function(a){a.p()});!this.he&&this.g&&ve(this.g);this.Qa=this.Md=this.g=this.vb=this.ra=k};function Y(a,b){return(a.R||(a.R=":"+(a.M.a++)[z](36)))+"."+b}function eg(a,b,c){a.ra&&dd(a.ra,b,c)}
Q.removeChild=function(a,b){if(a){var c=gc(a)?a:a.R||(a.R=":"+(a.M.a++)[z](36)),d;if(this.vb&&c){d=this.vb;d=c in d?d[c]:void 0;d=d||k}else d=k;a=d;if(c&&a){sd(this.vb,c);fd(this.ra,a);if(b){a.L();a.g&&ve(a.g)}c=a;if(c==k)g(ba("Unable to set parent component"));c.Qa=k;bg.s.jc[L](c,k)}}if(!a)g(ba("Child is not in parent component"));return a};Q.gc=function(a){for(;this.ra&&this.ra[A]!=0;)this[ib](this.ra?this.ra[0]||k:k,a)};function fg(a,b,c,d,e,f,h,j){var o,r=c.offsetParent;if(r){var y=r[N]=="HTML"||r[N]=="BODY";if(!y||Cf(r,"position")!="static"){o=If(r);y||(o=md(o,new ld(r[vb],r[Ca])))}}y=a;r=Mf(y);var s=Hf(y);if(s){y=r;var v=new xf(s[K],s.top,s[Wb]-s[K],s[xb]-s.top);s=u.max(y[K],v[K]);var Z=u.min(y[K]+y[D],v[K]+v[D]);if(s<=Z){var S=u.max(y.top,v.top);v=u.min(y.top+y[P],v.top+v[P]);if(S<=v){sa(y,s);y.top=S;na(y,Z-s);Aa(y,v-S)}}}y=r=r;s=ee(a);S=ee(c);if(s.a!=S.a){Z=s.a[J];S=Kf(Z,S.a[Hb]||S.a[Kb]);S=md(S,If(Z));if(V&&
!Fe(s))S=md(S,Ge(s));y.left+=S.x;y.top+=S.y}a=(b&4&&Jf(a)?b^2:b)&-5;b=new ld(a&2?r[K]+r[D]:r[K],a&1?r.top+r[P]:r.top);if(o)b=md(b,o);if(e){b.x+=(a&2?-1:1)*e.x;b.y+=(a&1?-1:1)*e.y}var C;if(h)if((C=Hf(c))&&o){C.top=u.max(0,C.top-o.y);C.right-=o.x;C.bottom-=o.y;sa(C,u.max(0,C[K]-o.x))}var pd;a:{e=b;c=c;a=d;d=f;C=C;f=h;j=j;e=e.Q();o=0;a=(a&4&&Jf(c)?a^2:a)&-5;h=Lf(c);j=j?j.Q():h;if(d||a!=0){if(a&2)e.x-=j[D]+(d?d[Wb]:0);else if(d)e.x+=d[K];if(a&1)e.y-=j[P]+(d?d[xb]:0);else if(d)e.y+=d.top}if(f){if(C){d=
e;o=j;C=C;f=f;a=0;if(d.x<C[K]&&f&1){d.x=C[K];a|=1}if(d.x<C[K]&&d.x+o[D]>C[Wb]&&f&16){o.width-=d.x+o[D]-C[Wb];a|=4}if(d.x+o[D]>C[Wb]&&f&1){d.x=u.max(C[Wb]-o[D],C[K]);a|=1}if(f&2)a|=(d.x<C[K]?16:0)|(d.x+o[D]>C[Wb]?32:0);if(d.y<C.top&&f&4){d.y=C.top;a|=2}if(d.y>=C.top&&d.y+o[P]>C[xb]&&f&32){o.height-=d.y+o[P]-C[xb];a|=8}if(d.y+o[P]>C[xb]&&f&4){d.y=u.max(C[xb]-o[P],C.top);a|=2}if(f&8)a|=(d.y<C.top?64:0)|(d.y+o[P]>C[xb]?128:0);C=a}else C=256;o=C;if(o&496){pd=o;break a}}Df(c,e);h=h==j?i:!h||!j?l:h[D]==
j[D]&&h[P]==j[P];if(!h){h=c;j=j;if(j instanceof nd){pd=j[P];j=j[D]}else g(ba("missing height argument"));na(h[I],Ef(j,i));Aa(h[I],Ef(pd,i))}pd=o}return pd};var gg="A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff",hg="\u0591-\u07ff\ufb1d-\ufdff\ufe70-\ufefc";ia("["+hg+"]");ia("["+gg+"]");ia("^["+gg+"]");ia("^["+hg+"]");ia("^[^"+hg+"]*["+gg+"]");ia("^[^"+gg+"]*["+hg+"]");ia("["+gg+"][^"+hg+"]*$");ia("["+hg+"][^"+gg+"]*$");var ig=ia("^(ar|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)");function jg(a){this.a=Se?[]:"";a!=k&&this.G[Fb](this,arguments)}jg[B].ea=function(a){this.clear();this.G(a)};if(Se){jg[B].b=0;jg[B].G=function(a,b){if(b==k)this.a[this.b++]=a;else{this.a[x][Fb](this.a,arguments);this.b=this.a[A]}return this}}else jg[B].G=function(a,b){this.a+=a;if(b!=k)for(var c=1;c<arguments[A];c++)this.a+=arguments[c];return this};jg[B].clear=function(){if(Se){la(this.a,0);this.b=0}else this.a=""};ka(jg[B],function(){if(Se){var a=this.a[Rb]("");this.clear();a&&this.G(a);return a}else return this.a});var kg=jg;function lg(a,b){var c=b||new kg;c.G('<head><meta http-equiv="Content-Type" content="text/html; charset=UTF8"><link rel="stylesheet" type="text/css" href="',a.A,'"></head><body scroll="no" style="margin:0px;overflow:hidden" dir="',a.dir,'" marginHeight=0 marginWidth=0 leftMargin=0 topMargin=0 border=0><div id="',a.id,'" class="goog-te-menu"></div></body>');if(!b)return c[z]()}
function mg(a,b){var c=b||new kg;c.G('<head><meta http-equiv="Content-Type" content="text/html; charset=UTF8"><link rel="stylesheet" type="text/css" href="',a.A,'"></head><body class="goog-te-banner" scroll="no" border=0 dir="',a.dir,'"><table border=0 cellspacing=0 cellpadding=0 width=100% height=100%><tr valign=middle><td width=1 nowrap><a href="',a.ec,'" class="goog-logo-link" target="_blank"><img src="',a.Ca,'" alt="Google ',"Translate",'"></a></td>',a.Ha?'<td width=1><img src="'+a.xa+'" width="9" height="15" title="'+
a.Ha+'" alt="'+a.Ha+'" style="background-image:url('+a.Sa+');background-position:-56px 0px;margin:0 4px"></td>':"",'<td class="goog-te-banner-margin"></td><td><table border=0 cellspacing=0 cellpadding=0 height=100%><tr id="',a.Td,'" style="display:none" valign=middle><td nowrap><span class="goog-te-banner-content">',a.Sd,'</span></td><td class="goog-te-banner-margin"></td><td nowrap><div class="goog-te-button"><div><button id="',a.ad,'"><b>',"Translate",'</b></button></div></div></td><td class="goog-te-banner-margin"></td><td nowrap><div class="goog-te-button"><div><button id="',
a.Nd,'"></button></div></div></td></tr><tr id="',a.Rd,'" style="display:none" valign=middle><td><span class="goog-te-banner-content">',"Translation in progress",'&nbsp;<span dir="ltr">(<b id="',a.Qd,'"></b>%)</span>&nbsp;<img src="',a.Ld,'"></span></td><td class="goog-te-banner-margin"></td><td nowrap><div class="goog-te-button"><div><button id="',a.Zc,'">',"Cancel",'</button></div></div></td></tr><tr id="',a.gd,'" style="display:none"><td><span class="goog-te-banner-content">',a.fd,'</span></td><td class="goog-te-banner-margin"></td><td nowrap><div class="goog-te-button"><div><button id="',
a.Ud,'">',"Show original",'</button></div></div></td></tr><tr id="',a.ed,'" style="display:none" valign=middle><td><span id="',a.dd,'" class="goog-te-banner-content"></span></td></tr></table></td><td width=1><a href="',a.Kd,'" target="_blank" style="white-space:nowrap">',"Learn more",'</a></td><td width=1><a id="',a.$c,'" class="goog-close-link" href="javascript:void(0)" title="',"Close",'"><img src="',a.xa,'" width="15" height="15" alt="',"Close",'" style="background-image:url(',a.Sa,');background-position:-28px 0px"></a></td></tr></table></body>');
if(!b)return c[z]()}function ng(a,b){var c=b||new kg;c.G('<span id="',a.id,'"></span>');if(!b)return c[z]()}function og(a,b){var c=b||new kg;c.G(a.Oc,'<div id="',a.id,'"></div>',a.Nc);if(!b)return c[z]()}
function pg(a,b){var c=b||new kg;c.G('<head><meta http-equiv="Content-Type" content="text/html; charset=UTF8"><link rel="stylesheet" type="text/css" href="',a.A,'"></head><body class="goog-te-ftab ',a.xb,'" scroll="no" style="overflow:hidden" dir="',a.dir,'"><a id="',a.ge,'" href="javascript:void(0)" class="goog-te-ftab-link"><img src="',a.xa,'" style="background-image:url(',a.Sa,');background-position:-65px 0px"><span>',"Translate","</span></a></body>");if(!b)return c[z]()}
function qg(a,b){var c=b||new kg;c.G(".",a[Ia]," {z-index:9999999; overflow:visible; position:fixed; _position:absolute;",a.top||a.top==0?"top:"+a.top+"px; _top:expression(("+a.top+"+(hack1=document.documentElement.scrollTop||document.body.scrollTop))+'px');":"top:auto;",a[K]||a[K]==0?"left:"+a[K]+"px; _left:expression(("+a[K]+"+(hack2=document.documentElement.scrollLeft||document.body.scrollLeft))+'px');":"left:auto;",a[xb]||a[xb]==0?"bottom:"+a[xb]+"px; _top:expression((-"+a[xb]+"-document.getElementById('"+
a.id+"').offsetHeight+(hack3=document.documentElement.clientHeight||document.body.clientHeight)+(hack4=document.documentElement.scrollTop||document.body.scrollTop))+'px');":"bottom:auto;",a[Wb]||a[Wb]==0?"right:"+a[Wb]+"px; _left:expression((-"+a[Wb]+"-document.getElementById('"+a.id+"').offsetWidth+(hack5=document.documentElement.clientWidth||document.body.clientWidth)+(hack6=document.documentElement.scrollLeft||document.body.scrollLeft))+'px');":"right:auto;","}");if(!b)return c[z]()}
function rg(a,b){var c=b||new kg;c.G('<head><meta http-equiv="Content-Type" content="text/html; charset=UTF8"><link rel="stylesheet" type="text/css" href="',a.A,'"></head><body scroll="no" style="margin:0px;overflow:hidden" dir="',a.dir,'" marginHeight=0 marginWidth=0 leftMargin=0 topMargin=0 border=0><div id="content" class="goog-te-balloon"><table border=0 cellspacing=0 cellpadding=0 width=100%><tr valign=middle><td nowrap><b>',"Original text:",'</b></td><td id="logo" width=1 nowrap>',a.bc?"<span style=\"display:inline-block;vertical-align:middle;height:15px; width:51px;filter:progid:DXImageTransform.Microsoft.AlphaImageLoader( src='"+
a.Ca+"',sizingMethod='scale');\"></span>":'<img src="'+a.Ca+'">','</td><td width=8></td><td width=1 nowrap><a id="close" href="javascript:void(0)" title="',"Close",'"><img src="',a.xa,'" width="15" height="15" style="background-image:url(',a.Sa,');background-position:-28px 0px"></a></td></tr></table><div id="original" class="goog-te-balloon-text"></div><div id="zippy" class="goog-te-balloon-zippy" style="display:none"><img id="zippy_img" class="plus" width="12" height="12" src="',a.xa,'"><span>',
"Contribute a better translation",'</span></div><div id="feedback" style="display:none"><iframe name="feedback-frame" frameBorder=0 style="width:100%;display:none"></iframe></div><div class="goog-te-balloon-form" style="display:none"><form id="suggestForm" target="feedback-frame" method="post"><input type="hidden" name="gtrans"><input type="hidden" name="hl"><input type="hidden" name="text"><input type="hidden" name="langpair"><input type="hidden" name="oe" value="UTF-8">');for(var d=a.ba,e=d[A],
f=0;f<e;f++){var h=d[f];c.G('<input type="hidden" name="',h,'" />')}c.G('<textarea rows="3" name="utrans"></textarea><div style="text-align:',a.dir=="rtl"?"left":"right",'"><input type="submit" value="',"Contribute",'"></div></form></div><div id="forward" class="goog-te-balloon-footer" style="display:none"><a id="forward_link" href="javascript:void(0)">',"Contribute a better translation","</a></div></div></body>");if(!b)return c[z]()};function sg(a){for(var b={},c=0;c<a[A];++c)b[a[c]]=i;return b}function tg(a,b,c){this.c=[];this.f=a||0;if(b||!c)this.d=b||1;else this.j=c;this.a=0;this.b=i}tg[B].add=function(a){this.c[x](a)};tg[B].go=function(){if(this.b){this.b=l;p[Sa](T(this.h,this),this.f)}};oa(tg[B],function(){this.b=i});
tg[B].h=function(){if(!this.b){if(this.d)for(var a=0;a<this.d;++a)if(this.c[this.a]){this.c[this.a][L]();this.a++}else{this.b=i;return}else for(a=(new Date).getTime();(new Date).getTime()-a<this.j;)if(this.c[this.a]){this.c[this.a][L]();this.a++}else{this.b=i;return}p[Sa](T(this.h,this),this.f)}};function ug(a){this.gb=a?[a]:[];this.Ea=[0];this.ya=l}function vg(a,b){if(a.ya)return b;a.Ea[x](0);var c=a.Ea[A]-1;return T(function(){this.Ea[c]++;b&&b[Fb](k,arguments);wg(this)},a)}
function xg(a,b){if(a.ya)return b;return T(function(){if(this.ya)b[Fb](k,arguments);else{var c=arguments;this.gb[x](function(){b[Fb](k,c)})}},a)}ug[B].oa=function(){this.Ea[0]=1;wg(this)};function wg(a){for(var b=0;b<a.Ea[A];++b)if(a.Ea[b]==0)return;a.ya=i;for(b=0;b<a.gb[A];++b){var c=a.gb[b];a.gb[b]=k;c[L]()}a.gb=[];a.Ea=[]}function yg(a){this.Tc=a;this.pa=this.Mb=l}function zg(a,b){return T(function(){b&&b[Fb](k,arguments);if(this.pa){if(!this.Mb){this.Tc[L]();this.Mb=i}}else this.Mb=i},a)}
yg[B].oa=function(){if(!this.pa){this.pa=i;this.Mb&&this.Tc[L]()}};function Ag(a,b,c,d){this.La=b;this.d=a;this.f=c||0;this.o=d||0;this.a=this.pa=l}Ag[B].go=function(){this.pa||this.c()};Ag[B].c=function(){if(this.pa=(this.a=!!this.d[L]())||--this.o<=0){this.La[L](k,this.a);this.b=0}else this.b=p[Sa](T(this.c,this),this.f)};oa(Ag[B],function(){this.b&&p[Ka](this.b);this.pa=i;this.La[L](k,this.a)});
function Bg(a){var b="";if(a)if(a[F]==3)b=n(a[Tb]);else if(a[F]==1&&(a[N]=="INPUT"||a[N]=="TEXTAREA"))b=a[Ya];else if(a[M]&&!a[M][Ob]&&a[M][F]==3)b=n(a[M][Tb]);return b}function Cg(a,b){if(a)if(a[F]==3)a.nodeValue=b;else if(a[F]==1)if(a[N]=="INPUT"||a[N]=="TEXTAREA")qa(a,b);else ze(a,b)}function Dg(a,b){return function(){a[H](b)}}
function Eg(a){a=Nc(a).toLowerCase()[E]("_","-");if(a=="zh-cn")return"zh-CN";else if(a=="zh-tw")return"zh-TW";var b=a[G]("-");a=b>=0?a[Ab](0,b):a;if(a=="zh")return"zh-CN";return a}function Fg(a){var b=[];for(var c in a)if(a[c]!==q[B][c]){var d=Rc(c);if(dc(a[c])=="array")for(var e=0;e<a[c][A];++e)b[x](d+"="+Rc(a[c][e]));else b[x](d+"="+Rc(a[c]))}return b[Rb]("&")}function Gg(a,b){var c=b||{};c.nca=a;c.client=yc;var d=new Image;d.src="//"+Hc+"/gen204?"+Fg(c);d.onload=function(){d.onload=k}}
function Hg(a,b){if((V||Gd)&&p[Za].hostname!=t.domain){Ig=Ig?Ig+1:1;var c="f"+Ig+"_"+nc()[z](36);p[c]=function(){p[c]=m;a.src="javascript:void(0)";b&&p[Sa](function(){b()},0)};a.src="javascript:void(document.write(\"<script>document.domain='"+t.domain+"';parent['"+c+"']();<\/script>\"))"}else b&&b()}var Ig;function Jg(){var a={};try{for(var b in q[B]){var c=q[B][b];delete q[B][b];a[b]=c}}catch(d){return{}}return a}function Kg(a){for(var b in a)q[B][b]=a[b]};function Lg(a,b){bg[L](this,b);this.e=a||{};this.e.A||(this.e.A=Gc);this.e.$=this.e.$;this.e.Ga=!!this.e.Ga;this.e.ba=this.e.ba||[];this.d=new Wf(this);this.j=new ug}U(Lg,bg);Q=Lg[B];
Q.t=function(){this.g=this.b[qb]("div");this.g[I].position="absolute";this.g[I].zIndex=1073741824;this.g[I].top="-9999em";this.f=l;var a={id:Y(this,"container")},b=this.g;a=a;var c=new kg;c.G('<iframe id="',a.id,'" class="goog-te-balloon-frame skiptranslate" frameBorder=0 src="javascript:\'\'" style="visibility:visible"></iframe>');a=c[z]();pa(b,a)};
Q.Z=function(){Lg.s.Z[L](this);var a={A:this.e.A,dir:ig[Ga](pc)?"rtl":"ltr",Ca:Fc,bc:V&&!Yd("7.0"),xa:Jc,Sa:Bc,ba:this.e.ba};this.g.id=Y(this,"balloonContainer");this.z=this.b.n(Y(this,"container"));X(this.d,this.z,"load",this.be);Hg(this.z,T(function(){var b=ye(this.z);b[gb](rg(a));b[db]()},this))};
Q.be=function(){W(this.g,i);var a=new fe(ye(this.z));this.a=a;this.k=a.n("content");this.m=a.n("original");var b=V?this.z:this.z[Pb]||ye(this.z)[Hb]||ye(this.z)[Kb];X(this.d,b,"mouseout",this.Ed);X(this.d,b,"mouseover",this.Fd);X(this.d,a.n("close"),"click",Dg(this,"close"));if(V)na(this.k[I],"100%");this.e.Ga||W(a.n("logo"),l);this.h=200;if(this.e.$!=0){this.c=a.n("suggestForm");this.c.action=Lc;X(this.d,this.c,"submit",this.ud);if(this.e.$==1){this.l=a.n("zippy_img");this.B=a.n("feedback");a=a.n("zippy");
X(this.d,a,"click",this.Ec);W(a,i);for(a=a[M];a;a=a[Ob])this.h+=a[Va]}else if(this.e.$==2){ta(this.c,"_blank");W(a.n("forward"),i);X(this.d,a.n("forward_link"),"click",T(this.c.submit,this.c))}}W(this.g,l);this[H]("load");this.j.oa()};Q.L=function(){Lg.s.L[L](this);this.d.p();this.a=this.d=k;ve(this.z);this.B=this.l=this.c=this.m=this.k=this.z=k};Q.Ec=function(){if(this.l[Ia]=="plus"){ma(this.l,"minus");W(this.c[O],i);this[H]("open_form")}else{ma(this.l,"plus");W(this.c[O],l);this[H]("close_form")}Mg(this)};
Q.Ed=function(){this[H]("mouseout")};Q.Fd=function(){this[H]("mouseover")};Q.ud=function(){this.e.$==1&&this.Ec()};Q.ic=function(a,b,c,d,e){if(this.j.ya){ze(this.m,Nc(a||""));if(this.c){qa(this.c.gtrans,b||"");qa(this.c.hl,pc);qa(this.c[Ma],a||"");qa(this.c.langpair,c+"|"+d);qa(this.c.utrans,Nc(b||""));for(a=0;a<this.e.ba[A];++a){b=this.e.ba[a];qa(this.c[b],e&&e[b]||"")}}}else xg(this.j,T(this.ic,this,a,b,c,d,e))[L]()};
function Mg(a){var b=Qf(a.k);if(b[D]<a.h)na(b,a.h);if(b[P]<=0)Aa(b,a.h);Rf(a.z,b);Rf(a.g,b)}Q.reset=function(a){if(this.j.ya){this.g[I].top="-9999em";W(this.g,i);var b=this.a[qb]("span");this.m[M]&&b[w](this.m[M].cloneNode(i));b[I].whiteSpace="nowrap";this.k[w](b);var c=b[Va]+20;this.k[ib](b);b=this.b.a[J][Va]/2;if(a&&c>a)c=a;if(c>b)c=b;if(c<this.h)c=this.h;na(this.z[I],c+"px");Mg(this);if(this.e.$==1){ma(this.l,"plus");W(this.c[O],l);W(this.B,l)}}else xg(this.j,T(this[Jb],this,a))[L]()};Q.ga=Yb("f");
Q.P=function(a,b,c){if(this.j.ya){if(a){if(b){var d=0,e=0,f=0;if(c&&c[A]){for(var h=NaN,j=NaN,o=NaN,r=NaN,y=0;y<c[A];++y){var s=Mf(c[y]);if(s[D]&&s[P]){h<s[K]||(h=s[K]);j>s[K]+s[D]||(j=s[K]+s[D]);o<s.top||(o=s.top);r>s.top+s[P]||(r=s.top+s[P])}}this[Jb](j-h);if(h&&o&&r){s=Mf(b);d=h-s[K];e=o-s.top;f=s.top+s[P]-r}}else this[Jb]();c=fg(b,4,this.g,5,new ld(d||0,-4+(e||0)),m,9);if(c&496)fg(b,5,this.g,4,new ld(d||0,-4+(f||0)),m,5)}}else{this[Jb]();W(this.g,a)}this.f=a}else xg(this.j,T(this.P,this,a,b,c))[L]()};function Ng(a,b){this.e=a||{};this.e.$=a.$;this.e.Ga=!!a.Ga;this.e.uc=ea(a.uc,10)||300;this.e.ba=a.ba;this.j=0;this.d={};this.c=l;this.b=new Wf(this);this.f=k;this.k={};this.a=new Lg({A:Gc,$:this.e.$,Ga:this.e.Ga,ba:this.e.ba},b);this.a.ma(Ee(b||ee())[J]);X(this.b,this.a,"open_form",this.md);X(this.b,this.a,"close_form",this.kd);X(this.b,this.a,"mouseout",this.Cc);X(this.b,this.a,"mouseover",this.nd);X(this.b,this.a,"close",this.ld);this.h=""}U(Ng,Mc);
function Og(a,b,c,d,e,f){a.d[++a.j]={text:c,fe:d,Yd:e||a.l,ee:f||a.m,la:b};for(c=0;c<b[A];++c)if(b[c]){X(a.b,b[c],"mouseout",a.Cc);X(a.b,b[c],"mouseover",T(a.Bd,a,a.j,b[c]))}return a.j[z]()}function Pg(a,b){var c=a.d[b];if(c){for(var d=0;d<c.la[A];++d)if(c.la[d]){Yf(a.b,c.la[d],"mouseout");Yf(a.b,c.la[d],"mouseover")}delete a.d[b]}}Q=Ng[B];Q.r=function(){Qg(this);for(var a in this.d)Pg(this,a);this.b.p();this.b=k;this.a.p();this.a=k};function Rg(a){if(a.f){p[Ka](a.f);a.f=k}}
function Sg(a,b){Rg(a);a.f=p[Sa](T(function(c){c[L](this);this.f=k},a,b),a.e.uc)}Q.md=function(){this.c=i};Q.kd=function(){Rg(this);this.c=l};function Tg(a,b,c){if(a=a.d[b]){c=c||typeof c=="undefined";for(b=0;b<a.la[A];++b)if(a.la[b]){yf(a.la[b],"backgroundColor",c?"#E6ECF9":"");yf(a.la[b],"color",c?"#000":"")}}}Q.Cc=function(){this.c||Sg(this,function(){Tg(this,this.h,l);this.a.P(l);this.c=l})};Q.nd=function(){this.c||Rg(this)};function Qg(a){a.c=i;Rg(a);Tg(a,a.h,l);a.a.P(l);a.c=l}Q.ld=function(){Qg(this)};
Q.Bd=function(a,b){this.c||Sg(this,function(){Tg(this,this.h,l);this.h=a;Tg(this,a);var c=this.d[a];this.e.$!=0?this.a.ic(c[Ma],c.fe,c.Yd,c.ee,this.k):this.a.ic(c[Ma]);this.a.P(i,b,c.la);this.c=l})};function Ug(a,b,c,d,e,f){this.a=a;this.ja=b;this.B=d;this.l=c;this.h=e;this.j=ja(this.a[A]);this.b=ja(this.a[A]);this.c=[];this.d=[];this.f=this.k=l;this.m=f||"transparent"}U(Ug,Mc);function Vg(a){for(var b=0;b<a.a[A];++b)try{if(!a.a[b]||!a.a[b][O]){a.a[b]=k;a.b[b]=k}}catch(c){a.a[b]=k;a.b[b]=k}}
xa(Ug[B],function(){if(this.f){this.f=l;if(this.d[A]>0){for(var a=0;a<this.d[A];++a)Pg(this.h,this.d[a]);this.d=[]}Vg(this);for(a=0;a<this.a[A];++a)if(this.j[a]&&this.a[a]){Cg(this.a[a],this.l[a]);if(this.b[a]){var b=this.b[a];this.a[a]=b[M];b=b;var c=void 0,d=b[O];if(d&&d[F]!=11)if(b.removeNode)b.removeNode(l);else{for(;c=b[M];)d[ab](c,b);ve(b)}this.b[a]=k}this.j[a]=l}}});
function Wg(a,b){function c(v,Z){v.background=Z;v.border="0";v.fontSize="100%";v.margin="0";v.outline="0";v.padding="0";v.verticalAlign="baseline";ya(v,"inline")}if(b&&b[a.ja]){a.c=b[a.ja];a.k=i}if(!(!a.k||a.f||a.c.cd)){a.f=i;Vg(a);for(var d=0;d<a.a[A];++d)if(!a.j[d]&&a.a[d]){var e=a.a[d];if(e[O]&&(e[O][N]=="OPTION"||e[O][N]=="TITLE")||e[N]=="INPUT"||e[N]=="TEXTAREA"){Cg(a.a[d],"");a.b[d]=k}else{var f=e[hb]?e[hb][qb]("font"):t[qb]("font");c(f[I],a.m);we(f,e);a.b[d]=f;a.a[d]=f}a.j[d]=i}for(d=0;d<a.c[A];++d){var h=
a.c[d],j=h.Lc;if(!j){for(var o=[],r=0;r<h.aa[A];++r)o[x](a.l[h.aa[r][La]]);j=o[Rb](" ")}var y=[];o=[];for(r=0;r<h.aa[A];++r){o[x](h.aa[r][Ma]);var s=h.aa[r];if(e=a.b[s[La]]){f=e[hb]?e[hb][qb]("font"):t[qb]("font");y[x](f);c(f[I],a.m);a.h||(f.title=j);Cg(f,s[Ma]);e[w](f);d!=0&&e[M]!=f&&ue(f[hb]?f[hb][Xa](" "):t[Xa](" "),f)}else a.a[s[La]]&&Cg(a.a[s[La]],Bg(a.a[s[La]])+s[Ma])}a.h&&a.d[x](Og(a.h,y,j,o[Rb]("")))}for(d=0;d<a.a[A];++d){e=a.b[d];f=a.l[d];if(e){for(h=e[M];h;h=h[Ob]){j=Oc(Bg(h));Cg(h,j);if(j)break}for(h=
e[mb];h;h=h.previousSibling){j=Pc(Bg(h));Cg(h,j);if(j)break}h=f[Ab](0,f[A]-Oc(f)[A]);(j=e[M])?Cg(j,h+Bg(j)):re(e,e[hb]?e[hb][Xa](h):t[Xa](h));j=e[mb];h=f[Ab](Pc(f)[A]);j?Cg(j,Bg(j)+h):re(e,e[hb]?e[hb][Xa](h):t[Xa](h))}else Cg(a.a[d],f[Ab](0,f[A]-Oc(f)[A])+Nc(Bg(a.a[d]))+f[Ab](Pc(f)[A]))}}}Ug[B].r=function(){Ug.s.r[L](this);this[Db]();this.a=k};function Xg(a){bg[L](this,a);this.h=new Wf(this)}U(Xg,bg);Q=Xg[B];Q.t=function(){this.g=this.b[qb]("select");ma(this.g,"goog-te-combo")};Q.Z=function(){Xg.s.Z[L](this);this.vc()};Q.vc=function(){mf(this.g,"change",Dg(this,"chg_lang"));this[H]("load")};function Yg(a,b){if(a.g[O]!=b){a.g[O][ib](a.g);b[w](a.g)}}Q.ta=function(a){this.b.gc(this.g);for(var b in a)if(a[b]!==q[B][b]){var c=this.b.t("option",{value:b});this.b.Hb(c,a[b]);this.g[w](c)}this.g.selectedIndex=0};Q.Ab=function(){return this.g[Ya]};
Q.ua=function(a){if(this.g[Ya]!=a)for(var b=0,c;c=this.g.options[$a](b);++b)if(c[Ya]==a){this.g.selectedIndex=b;return}};Q.Yb=function(a){if(dc(a)=="undefined")return this.g.options[$a](this.g.selectedIndex)[Ma];for(var b=0,c;c=this.g.options[$a](b);++b)if(c[Ya]==a)return c[Ma]};Q.L=function(){Xg.s.L[L](this);this.h.p();this.h=k};Q.ab=function(a){this.g.disabled=!a};function Zg(a,b){Xg[L](this,b);this.e=a||{};this.e.A||(this.e.A=Gc)}U(Zg,Xg);Q=Zg[B];
Q.t=function(){this.g=this.b[qb]("a");ma(this.g,"goog-te-menu-value");this.g.href="javascript:void(0)";this.K=this.b.t("span");this.g[w](this.K);if(this.e.hd){this.g[w](this.b.t("img",{src:Jc,width:1,height:1}));this.g[w](this.b.t("span",{style:"border-left:1px solid #bbb"},"\u200b"));this.g[w](this.b.t("img",{src:Jc,width:1,height:1}));this.f=this.b.t("span",{style:"color:#9b9b9b"},"\u25bc");this.g[w](this.f);this.l=this.f}else{this.d=this.b.t("img",{src:Jc,style:"background-image:url("+Bc+");background-position:-14px 0px;border:none",
width:14,height:14});this.g[w](this.d);this.l=this.d}this.C=ne("iframe",{frameBorder:0,"class":"goog-te-menu-frame skiptranslate"});this.C[I].visibility="visible";W(this.C,l);t[J][w](this.C)};Q.vc=function(){var a={dir:ig[Ga](pc)?"rtl":"ltr",A:this.e.A,id:Y(this,"menuBody")};X(this.h,this.C,"load",this.ae);Hg(this.C,T(function(){var b=ye(this.C);b[gb](lg(a));b[db]()},this))};
Q.ae=function(){this.a=new fe(ye(this.C));this.j=this.a.n(Y(this,"menuBody"));X(this.h,this.g,"click",this.sd);V?X(this.h,this.C,"blur",this.ac):X(this.h,this.C[Pb]||ye(this.C)[Hb]||ye(this.C)[Kb],"blur",this.ac);this[H]("load")};Q.ta=function(){};Q.Ad=function(a){if(this.k!=a[fb][Ya]){this.ua(a[fb][Ya]);this[H]("chg_lang")}this.ac()};Q.sd=function(){this.Jb();(this.C[Pb]||ye(this.C)[Hb]||ye(this.C)[Kb]).focus();this.O=i};Q.ac=function(){if(this.O){this.O=l;this.Jb(l)}};
Q.Jb=function(a){if(a==l){this.d&&yf(this.d,"backgroundPosition","-14px 0px");this.f&&yf(this.f,"color","#9b9b9b");W(this.C,l)}else{a=Kf(this.l,p);a.y+=this.l[Qb];a.x+=this.l[Va]-this.m[D]>>1;if(V&&!Yd("7.0")){var b=t[J];a.y-=b.offsetTop;a.x-=b.offsetLeft}else{b=me(t);a.y-=b.y;a.x-=b.x}b=le(p);if(a.x>b[D]-this.m[D])a.x=b[D]-this.m[D];if(a.x<0)a.x=0;if(a.y>b[P]-this.m[P])a.y=b[P]-this.m[P];if(a.y<0)a.y=0;Df(this.C,a);this.d&&yf(this.d,"backgroundPosition","0px 0px");this.f&&yf(this.f,"color","#d5d5d5");
W(this.C,i)}};Q.Ab=Yb("k");Q.ua=function(a){if(this.k!=a){var b=this.Yb(a);if(b){this.k=a;this.b.Hb(this.K,b)}}};Q.Yb=function(){};Q.L=function(){Zg.s.L[L](this);ve(this.C);this.j=this.a=this.C=this.l=this.f=this.d=this.K=k};function $g(a,b){Zg[L](this,a,b);this.e=a||{};this.e.A||(this.e.A=Gc)}U($g,Zg);Q=$g[B];
Q.ta=function(a){this.a.gc(this.j);W(this.C,i);this.B=a;this.c=[];for(var b in a)if(a[b]!==q[B][b]){var c={Va:this.a.t("a",{className:"goog-te-menu2-item-selected",href:"javascript:void(0)",value:b})};this.c[x](c);var d=this.a.t("div",{style:"white-space:nowrap"});this.a[w](c.Va,d);this.a[w](d,this.a.t("span",{className:"indicator"},"\u203a"));this.a[w](d,this.a.t("span",{className:"text"},a[b]));X(this.h,c.Va,"click",this.Ad)}a=this.c[A]-1;a=u[Pa]((a-a%11)/11)+1;this.H=this.a.t("table",{cellspacing:0,
cellpadding:0,border:0});c=this.a.t("tbody");b=this.a.t("tr",{valign:"top"});ma(this.j,"goog-te-menu2");this.a[w](this.j,this.H);this.a[w](this.H,c);this.a[w](c,b);for(d=c=0;c<a;++c){var e=this.a.t("td");this.a[w](b,e);for(var f=0;f<11&&d<this.c[A];++f,++d)this.a[w](e,this.c[d].Va);if(c!=a-1){e=this.a.t("td",{"class":"goog-te-menu2-colpad"},"\u00a0");this.a[w](b,e)}}this.k=k;this.ua(this.c[0].Va[Ya]);ah(this);W(this.C,l)};Q.Yb=function(a){a=dc(a)=="undefined"?this.k:a;return this.B[a]};
Q.ua=function(a){if(this.k!=a){$g.s.ua[L](this,a);for(var b=0;b<this.c[A];++b){var c=this.c[b];ma(c.Va,c.Va[Ya]==a?"goog-te-menu2-item-selected":"goog-te-menu2-item")}}};function ah(a){Rf(a.j,Qf(a.H));Rf(a.C,Qf(a.j));a.m=Qf(a.C)}Q.Jb=function(a){$g.s.Jb[L](this,a);a!=l&&ah(this)};Q.L=function(){$g.s.L[L](this);this.H=this.c=k};function bh(a){return a="Translated to: "+a}function ch(a){return a="View this page in: "+a};var dh="StopIteration"in R?R.StopIteration:ba("StopIteration");function eh(){}eh[B].Da=function(){g(dh)};eh[B].Xc=function(){return this};function fh(a,b,c,d,e){this.a=!!b;a&&this[Ib](a,d);this.b=e!=m?e:this.V||0;if(this.a)this.b*=-1;this.c=!c}U(fh,eh);Q=fh[B];Q.S=k;Q.V=0;Q.mc=l;Q.setPosition=function(a,b,c){if(this.S=a)this.V=typeof b=="number"?b:this.S[F]!=1?0:this.a?-1:1;if(typeof c=="number")this.b=c};Q.Q=function(){return new fh(this.S,this.a,!this.c,this.V,this.b)};function gh(a){var b=a.a?-1:1;if(a.V==b){a.V=b*-1;a.b+=a.V*(a.a?-1:1)}}
Q.Da=function(){var a;if(this.mc){if(!this.S||this.c&&this.b==0)g(dh);a=this.S;var b=this.a?-1:1;if(this.V==b){var c=this.a?a[mb]:a[M];c?this[Ib](c):this[Ib](a,b*-1)}else(c=this.a?a.previousSibling:a[Ob])?this[Ib](c):this[Ib](a[O],b*-1);this.b+=this.V*(this.a?-1:1)}else this.mc=i;a=this.S;if(!this.S)g(dh);return a};
Q.splice=function(){var a=this.S,b=this.a?1:-1;if(this.V==b){this.V=b*-1;this.b+=this.V*(this.a?-1:1)}this.a=!this.a;fh[B].Da[L](this);this.a=!this.a;b=fc(arguments[0])?arguments[0]:arguments;for(var c=b[A]-1;c>=0;c--)a[O]&&a[O][ab](b[c],a[Ob]);ve(a)};var hh=ia("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");function ih(a,b,c){this.a=new fh;this.B=a;this.O=b;this.M=c}var jh=sg(["A","ABBR","ACRONYM","B","BASEFONT","BDO","BIG","CITE","CODE","DFN","EM","FONT","I","KBD","LABEL","Q","S","SMALL","SPAN","STRIKE","STRONG","SUB","SUP","TT","U","VAR"]),kh=sg(["APPLET","AREA","BASE","FRAME","FRAMESET","HR","IMG","LINK","META","MAP","OBJECT","PARAM","SCRIPT","STYLE","INPUT","TEXTAREA"]),lh=sg(["submit","button"]);ih[B].reset=function(a,b){this.h=[];this.k=[];this.D=i;this.j=[];this.m=[];mh(this,a,i,b)};
function mh(a,b,c,d){a.a[Ib](b,1,1);a.l=i;a.c=0;a.d=[c];a.f=!!d;a.a.mc||a.a.Da();nh(a)}
function oh(a,b){if(a.l){var c=0,d=[],e=[],f=0,h=[],j=a.f?27:13;do{var o=a.K;f+=a.c||(a.c=(a.f?Rc(o)[A]:o[A])+j);if(c!=0&&f>b)break;a.c=0;d[x](a.H);h[x](a.b);if(c==0){e[x](o);c++}else{if(c==1)e[0]="<a i=0>"+e[0]+"</a>";e[x]("<a i="+c++ +">");e[x](o);e[x]("</a>")}}while(nh(a));return new Ug(d,e[Rb](""),h,(d[A]==1?f-j:f)-a.c,a.O,a.M)}else if(a.h[A]>0){mh(a,a.h[Ha](),a.k[Ha](),a.f);return oh(a,b)}else if(a.j[A]>0){a.D=l;mh(a,a.j[Ha](),a.m[Ha](),a.f);return oh(a,b)}}
function ph(a){return a.d[a.d[A]-1]}
function nh(a){var b=i;try{for(;;){var c=a.H=a.a.S,d=a.a.V;if(d==-1){a.d.pop();b=b&&!!a.a.S&&(a.a.S[F]==3||jh[a.a.S[N]])}else if(c&&(c[F]==3||c[N]=="TEXTAREA"&&ed(be(c),"translate")||c[N]=="INPUT"&&(lh[c[Eb]]||ed(be(c),"translate")))){gh(a.a);if(ph(a)){a.b=Bg(c);var e=Nc(a.b[E](/\xa0|[ \t]+/g," "));e||(a.b=e);if(a.b){a.K=Sc(a.b);a.a.Da();break}}}else if(d==1){if(qh(c))gh(a.a);else if(c[N]=="IFRAME"){gh(a.a);try{var f;if(!(f=!c.src[nb](/https?:\/\//))){var h,j=c.src[nb](hh)[3]||k;h=j&&ha(j);f=h==p[Za].hostname}if(f){var o=
c[Pb][Ta][Ub];if(o){a.h[x](o);a.k[x](ph(a))}}}catch(r){}}else if(a.D&&!(c[Va]&&c[Qb])){gh(a.a);a.j[x](c);a.m[x](ph(a))}else{var y=a,s=c,v=!ed(be(s),"notranslate")&&(ed(be(s),"translate")||ph(y));y.d[x](v)}b=b&&ph(a)&&!!a.a.S&&(a.a.S[F]==3||jh[a.a.S[N]]);a.B&&ph(a)&&c[N]=="A"&&c[zb]&&a.B(c)}a.a.Da()}}catch(Z){if(Z!=dh)g(Z);a.l=l;a.b=k;b=l}return b}function qh(a){return a[F]!=3&&(!a[N]||kh[a[N]]||ed(be(a),"skiptranslate"))};function rh(a,b){bg[L](this,b);this.d=new Wf(this);this.e=a||{};this.e.A||(this.e.A=Gc);this.e.lc=l;yf(this.b.a[J],"position","relative");yf(this.b.a[J],"minHeight","100%");yf(this.b.a[Ub],"height","100%");yf(this.b.a[J],"top","0px");if(V){p._bannerquirkfixleft=-ea("0"+this.b.a[J].leftMargin,10);p._bannerquirkfixtop=-ea("0"+this.b.a[J].topMargin,10)-40}}U(rh,bg);Q=rh[B];Q.ma=function(){var a=this.b.a[J][M];dg(this,a[O],a)};
Q.t=function(){this.g=this.b[qb]("div");this.f=l;W(this.g,l);ce(this.g,"skiptranslate");var a={id:Y(this,"container")},b=this.g;a=a;var c=new kg;c.G('<iframe id="',a.id,'" class="goog-te-banner-frame skiptranslate" frameBorder=0 src="javascript:\'\'" style="visibility:visible"></iframe>');a=c[z]();pa(b,a)};
Q.Z=function(){rh.s.Z[L](this);var a={dir:ig[Ga](pc)?"rtl":"ltr",A:this.e.A,xa:Jc,ec:"http://translate.google.com",Ca:Kc,Sa:Bc,Td:Y(this,"promptSection"),ad:Y(this,"confirm"),Kd:"http://www.google.com/intl/en/help/faq_translation.html#element",Rd:Y(this,"progressSection"),Qd:Y(this,"progressValue"),Ld:Ec,Zc:Y(this,"cancel"),gd:Y(this,"finishSection"),Ud:Y(this,"restore"),ed:Y(this,"errorSection"),dd:Y(this,"errorContent"),$c:Y(this,"close"),re:Bc,Nd:Y(this,"noAutoPopup")},b=[];this.e.lc&&b[x](ng({id:Y(this,
"promptSourceLang")}));b[x](ng({id:Y(this,"promptTargetLang")}));a.Sd=ch[Fb](k,b);b=[];this.e.lc&&b[x](ng({id:Y(this,"finishSourceLang")}));b[x](ng({id:Y(this,"finishTargetLang")}));a.fd=bh[Fb](k,b);this.e.Ha&&(a.Ha=this.e.Ha);this.z=this.b.n(Y(this,"container"));X(this.d,this.z,"load",this.ce);Hg(this.z,T(function(){var c=ye(this.z);c[gb](mg(a));c[db]()},this))};
Q.ce=function(){this.a=new fe(ye(this.z));pa(this.a.n(Y(this,"errorContent")),"Error: The server could not complete your request. Try again later.");if(this.e.A==Gc){var a="url("+Ac+")";yf(this.a.a[J],"backgroundImage",a);for(var b=this.a.a[Sb]("button"),c=0;c<b[A];++c){yf(b[c][O],"backgroundImage",a);yf(b[c][O],"backgroundRepeat","repeat-x");yf(b[c][O],"backgroundPosition","0 -39px")}}if(this.e.lc)this.I=new $g(this.e,this.a);this.c=new $g(this.e,this.a);X(this.d,this.a.n(Y(this,"confirm")),"click",
Dg(this,"clk_confirm"));X(this.d,this.a.n(Y(this,"cancel")),"click",Dg(this,"clk_cancel"));X(this.d,this.a.n(Y(this,"restore")),"click",Dg(this,"clk_restore"));X(this.d,this.a.n(Y(this,"close")),"click",Dg(this,"clk_close"));this.k=this.a.n(Y(this,"noAutoPopup"));X(this.d,this.k,"click",Dg(this,"clk_no_ap"));this.I&&X(this.d,this.I,"chg_lang",Dg(this,"chg_src_lang"));X(this.d,this.c,"chg_lang",Dg(this,"chg_tgt_lang"));a=new ug(T(this[H],this,"load"));this.I&&X(this.d,this.I,"load",vg(a));X(this.d,
this.c,"load",vg(a));a.oa();this.I&&this.I.ma(this.a.n(Y(this,"promptSourceLang")));this.c.ma(this.a.n(Y(this,"promptTargetLang")))};Q.L=function(){this.P(l);rh.s.L[L](this);this.d.p();this.d=k;if(this.I){this.I.p();this.I=k}this.c.p();this.c=k;ve(this.z);this.hb=this.a=k};Q.ca=function(){return this.c.Ab()};function sh(a,b){a.I&&a.I.ua(b);if(a.l)if(a.l[b]){var c;c=c="Turn off for: "+a.l[b];a.a.Hb(a.k,c)}}Q.U=function(a){this.c.ua(a)};
function th(a,b,c,d){if(a.hb!=b){a.hb=b;if(b==0){a.I&&Yg(a.I,a.a.n(Y(a,"promptSourceLang")));if(a.j){var e=a.ca();a.c.ta(a.j);a.U(e)}Yg(a.c,a.a.n(Y(a,"promptTargetLang")))}else if(b==2){a.I&&Yg(a.I,a.a.n(Y(a,"finishSourceLang")));if(a.h){e=a.ca();a.c.ta(a.h);a.U(e)}Yg(a.c,a.a.n(Y(a,"finishTargetLang")))}e={};e[-1]=a.a.n(Y(a,"errorSection"));e[0]=a.a.n(Y(a,"promptSection"));e[1]=a.a.n(Y(a,"progressSection"));e[2]=a.a.n(Y(a,"finishSection"));for(var f in e)e[f]!==q[B][f]&&W(e[f],f==b)}c&&a.P(i);ya(a.k[O][O][I],
d?"block":"none")}Q.ga=Yb("f");
Q.P=function(a){if(this.f!=a){this.f=a;if(V)var b=ea("0"+this.b.a[J].leftMargin,10),c=ea("0"+this.b.a[J].topMargin,10);var d=this.b.a.compatMode=="BackCompat";if(a){yf(this.b.a[J],"top","40px");W(this.g,i);if(V)if(Yd("7.0")){p._bannerquirkfixleft=p._bannerquirkfixtop=0;if(d)this.b.a[J].topMargin=c+40}else if(d){this.m=i;this.b.a[J].topMargin=c+40;p._bannerquirkfixleft=p._bannerquirkfixtop=0}else{p._bannerquirkfixleft=-b;p._bannerquirkfixtop=-c-40}}else{yf(this.b.a[J],"top","0px");W(this.g,l);if(d&&
c>=40)this.b.a[J].topMargin=c-40}}};function uh(a,b){a.a.Hb(a.a.n(Y(a,"progressValue")),b)}Q.kc=function(a,b){this.j=a;this.h=b;this.c.ta(a)};function vh(a,b){bg[L](this,b);this.e=a||{};this.a=new Wf(this)}U(vh,bg);var wh={pe:0,le:1,me:2};Q=vh[B];
Q.t=function(){this.g=this.b[qb]("div");ce(this.g,"skiptranslate");ce(this.g,"goog-te-gadget");W(this.g,l);if(this.e.Ua==2)pa(this.g,og({id:Y(this,"targetLanguage"),Oc:"",Nc:""}));else{var a;a={bc:V&&!Yd("7.0"),Ca:Fc,ec:"http://translate.google.com"};var b=new kg;b.G('<span style="white-space:nowrap"><a class="goog-logo-link" href="',a.ec,'" target="_blank">',a.bc?"<span style=\"display:inline-block;vertical-align:middle;height:15px; width:51px;filter:progid:DXImageTransform.Microsoft.AlphaImageLoader( src='"+a.Ca+
"',sizingMethod='scale');\"></span>":'<img src="'+a.Ca+'">',"Translate","</a></span>");a=b[z]();a=a="Powered by "+a;pa(this.g,og({id:Y(this,"targetLanguage"),Oc:"",Nc:this.e.Ua==1?"&nbsp;&nbsp;"+a:a}))}};
Q.Z=function(){vh.s.Z[L](this);this.c=this.e.Ua==2?new $g({hd:i},this.b):new Xg(this.b);X(this.a,this.c,"chg_lang",Dg(this,"chg_tgt_lang"));X(this.a,this.c,"load",this.yd);var a=this.b.Wc(Y(this,"targetLanguage"));if(this.e.Ua==2){var b=this.b.t("img",{src:Jc,"class":"goog-te-gadget-icon"});b[I].backgroundImage="url("+Bc+")";b[I].backgroundPosition="-65px 0px";var c=this.b.t("span",{style:"vertical-align: middle"});a[w](b);a[w](c);this.c.ma(c);a[I].whiteSpace="nowrap";ma(a,"goog-te-gadget-simple")}else{this.c.ma(a);
if(this.e.Ua==1)ya(a[I],"inline")}};Q.yd=function(){this[H]("load")};Q.L=function(){vh.s.L[L](this);this.a.p();this.a=k;this.c.p();this.c=k};Q.ca=function(){return this.c.Ab()};Q.U=function(a){if(a=="")this.j&&this.c.ta(this.j);else this.h&&this.c.ta(this.h);this.c.ua(a)};Q.P=function(a){W(this.g,a)};Q.ab=function(a){this.c.ab(a)};Q.kc=function(a,b){this.j=a;this.h=b};function xh(a,b){bg[L](this,b);this.e=a||{};this.e.A||(this.e.A=Gc);this.a=new Wf(this)}U(xh,bg);var yh={ne:1,oe:2,je:3,ie:4};Q=xh[B];Q.t=function(){this.g=this.b[qb]("div");this.f=l;W(this.g,l);var a={id:Y(this,"container")},b=this.g;a=a;var c=new kg;c.G('<iframe id="',a.id,'" frameBorder=0 src="javascript:\'\'" class="goog-te-ftab-frame skiptranslate" style="visibility:visible"></iframe>');a=c[z]();pa(b,a)};
Q.Z=function(){xh.s.Z[L](this);var a={dir:ig[Ga](pc)?"rtl":"ltr",A:this.e.A,ge:Y(this,"translate"),xa:Jc,Sa:Bc};this.g.id=Y(this,"floatContainer");var b={id:this.g.id,className:"goog-te-ftab-float"};this.g.className+=" goog-te-ftab-float";switch(this.e.ib){case 2:a.xb="goog-float-top";b.top=0;Ba(b,20);break;case 3:a.xb="goog-float-bottom";wa(b,0);Ba(b,20);break;case 4:a.xb="goog-float-bottom";wa(b,0);sa(b,20);break;default:a.xb="goog-float-top";b.top=0;sa(b,20)}Of(qg(b),this.g);this.z=this.b.n(Y(this,
"container"));X(this.a,this.z,"load",this.de);Hg(this.z,T(function(){var c=ye(this.z);c[gb](pg(a));c[db]()},this))};Q.de=function(){var a=new fe(ye(this.z));this.c=a.n(Y(this,"translate"));X(this.a,this.c,"click",Dg(this,"clk_trans"));W(this.g,i);a=Qf(this.c);W(this.g,l);Rf(this.z,a);Rf(this.g,a);this[H]("load")};Q.L=function(){xh.s.L[L](this);this.a.p();this.a=k;ve(this.z);this.c=this.z=k};Q.ga=Yb("f");Q.P=function(a){this.f=a;W(this.g,a)};function zh(a){if(typeof a.za=="function")return a.za();if(gc(a))return a[Ua]("");if(fc(a)){for(var b=[],c=a[A],d=0;d<c;d++)b[x](a[d]);return b}return qd(a)}function Ah(a,b,c){if(typeof a[sb]=="function")a[sb](b,c);else if(fc(a)||gc(a))dd(a,b,c);else{var d;var e=a;if(typeof e.Oa=="function")d=e.Oa();else if(typeof e.za!="function")if(fc(e)||gc(e)){d=[];e=e[A];for(var f=0;f<e;f++)d[x](f);d=d}else d=rd(e);else d=void 0;e=zh(a);f=e[A];for(var h=0;h<f;h++)b[L](c,e[h],d&&d[h],a)}};function Bh(a){this.b={};this.a=[];var b=arguments[A];if(b>1){if(b%2)g(ba("Uneven number of arguments"));for(var c=0;c<b;c+=2)this.ea(arguments[c],arguments[c+1])}else if(a){c=a;if(c instanceof Bh){b=c.Oa();c=c.za()}else{b=rd(c);c=qd(c)}for(var d=0;d<b[A];d++)this.ea(b[d],c[d])}}Q=Bh[B];Q.o=0;Q.qb=0;Q.za=function(){Ch(this);for(var a=[],b=0;b<this.a[A];b++){var c=this.a[b];a[x](this.b[c])}return a};Q.Oa=function(){Ch(this);return this.a[Wa]()};Q.ia=function(a){return Dh(this.b,a)};
Q.clear=function(){this.b={};la(this.a,0);this.qb=this.o=0};Q.remove=function(a){if(Dh(this.b,a)){delete this.b[a];this.o--;this.qb++;this.a[A]>2*this.o&&Ch(this);return i}return l};function Ch(a){if(a.o!=a.a[A]){for(var b=0,c=0;b<a.a[A];){var d=a.a[b];if(Dh(a.b,d))a.a[c++]=d;b++}la(a.a,c)}if(a.o!=a.a[A]){var e={};for(c=b=0;b<a.a[A];){d=a.a[b];if(!Dh(e,d)){a.a[c++]=d;e[d]=1}b++}la(a.a,c)}}Q.qa=function(a,b){if(Dh(this.b,a))return this.b[a];return b};
Q.ea=function(a,b){if(!Dh(this.b,a)){this.o++;this.a[x](a);this.qb++}this.b[a]=b};Q.Q=function(){return new Bh(this)};Q.Xc=function(a){Ch(this);var b=0,c=this.a,d=this.b,e=this.qb,f=this,h=new eh;h.Da=function(){for(;;){if(e!=f.qb)g(ba("The map has changed since the iterator was created"));if(b>=c[A])g(dh);var j=c[b++];return a?j:d[j]}};return h};function Dh(a,b){return q[B][cb][L](a,b)};function Eh(a,b){var c;if(a instanceof Eh){Fh(this,b==k?a.Pa:b);Gh(this,a.sa);Hh(this,a.pb);Ih(this,a.Na);Jh(this,a.Za);Kh(this,a.Ya);Lh(this,a.a.Q());Mh(this,a.jb)}else if(a&&(c=n(a)[nb](hh))){Fh(this,!!b);Gh(this,c[1]||"",i);Hh(this,c[2]||"",i);Ih(this,c[3]||"",i);Jh(this,c[4]);Kh(this,c[5]||"",i);Lh(this,c[6]||"",i);Mh(this,c[7]||"",i)}else{Fh(this,!!b);this.a=new Nh(k,this,this.Pa)}}Q=Eh[B];Q.sa="";Q.pb="";Q.Na="";Q.Za=k;Q.Ya="";Q.jb="";Q.Id=l;Q.Pa=l;
ka(Q,function(){if(this.W)return this.W;var a=[];this.sa&&a[x](Oh(this.sa,Ph),":");if(this.Na){a[x]("//");this.pb&&a[x](Oh(this.pb,Ph),"@");a[x](Qh(this.Na));this.Za!=k&&a[x](":",n(this.Za))}if(this.Ya){this.Na&&this.Ya.charAt(0)!="/"&&a[x]("/");a[x](Oh(this.Ya,Rh))}var b=n(this.a);b&&a[x]("?",b);this.jb&&a[x]("#",Oh(this.jb,Sh));return this.W=a[Rb]("")});
Q.Q=function(){var a;a=this.sa;var b=this.pb,c=this.Na,d=this.Za,e=this.Ya,f=this.a.Q(),h=this.jb,j=new Eh(k,this.Pa);a&&Gh(j,a);b&&Hh(j,b);c&&Ih(j,c);d&&Jh(j,d);e&&Kh(j,e);f&&Lh(j,f);h&&Mh(j,h);return a=j};function Gh(a,b,c){Th(a);delete a.W;a.sa=c?b?ha(b):"":b;if(a.sa)a.sa=a.sa[E](/:$/,"");return a}function Hh(a,b,c){Th(a);delete a.W;a.pb=c?b?ha(b):"":b;return a}function Ih(a,b,c){Th(a);delete a.W;a.Na=c?b?ha(b):"":b;return a}
function Jh(a,b){Th(a);delete a.W;if(b){b=ga(b);if(isNaN(b)||b<0)g(ba("Bad port number "+b));a.Za=b}else a.Za=k;return a}function Kh(a,b,c){Th(a);delete a.W;a.Ya=c?b?ha(b):"":b;return a}function Lh(a,b,c){Th(a);delete a.W;if(b instanceof Nh){a.a=b;a.a.d=a;Uh(a.a,a.Pa)}else{c||(b=Oh(b,Vh));a.a=new Nh(b,a,a.Pa)}return a}
function Wh(a,b,c){Th(a);delete a.W;ec(c)||(c=[n(c)]);var d=a.a;b=b;c=c;Xh(d);Yh(d);b=Zh(d,b);if(d.ia(b)){var e=d.w.qa(b);if(ec(e))d.o-=e[A];else d.o--}if(c[A]>0){d.w.ea(b,c);d.o+=c[A]}return a}function Mh(a,b,c){Th(a);delete a.W;a.jb=c?b?ha(b):"":b;return a}function Th(a){if(a.Id)g(ba("Tried to modify a read-only Uri"))}function Fh(a,b){a.Pa=b;a.a&&Uh(a.a,b)}function Qh(a){if(gc(a))return da(a);return k}var $h=/^[a-zA-Z0-9\-_.!~*'():\/;?]*$/;
function Oh(a,b){var c=k;if(gc(a)){c=a;$h[Ga](c)||(c=encodeURI(a));if(c.search(b)>=0)c=c[E](b,ai)}return c}function ai(a){a=a.charCodeAt(0);return"%"+(a>>4&15)[z](16)+(a&15)[z](16)}var Ph=/[#\/\?@]/g,Rh=/[\#\?]/g,Vh=/[\#\?@]/g,Sh=/#/g;function Nh(a,b,c){this.a=a||k;this.d=b||k;this.c=!!c}
function Xh(a){if(!a.w){a.w=new Bh;if(a.a)for(var b=a.a[Ua]("&"),c=0;c<b[A];c++){var d=b[c][G]("="),e=k,f=k;if(d>=0){e=b[c][Ab](0,d);f=b[c][Ab](d+1)}else e=b[c];e=ha(e[E](/\+/g," "));e=Zh(a,e);a.add(e,f?ha(f[E](/\+/g," ")):"")}}}Q=Nh[B];Q.w=k;Q.o=k;Q.add=function(a,b){Xh(this);Yh(this);a=Zh(this,a);if(this.ia(a)){var c=this.w.qa(a);ec(c)?c[x](b):this.w.ea(a,[c,b])}else this.w.ea(a,b);this.o++;return this};
Q.remove=function(a){Xh(this);a=Zh(this,a);if(this.w.ia(a)){Yh(this);var b=this.w.qa(a);if(ec(b))this.o-=b[A];else this.o--;return this.w.remove(a)}return l};Q.clear=function(){Yh(this);this.w&&this.w.clear();this.o=0};Q.ia=function(a){Xh(this);a=Zh(this,a);return this.w.ia(a)};Q.Oa=function(){Xh(this);for(var a=this.w.za(),b=this.w.Oa(),c=[],d=0;d<b[A];d++){var e=a[d];if(ec(e))for(var f=0;f<e[A];f++)c[x](b[d]);else c[x](b[d])}return c};
Q.za=function(a){Xh(this);if(a){a=Zh(this,a);if(this.ia(a)){var b=this.w.qa(a);if(ec(b))return b;else{a=[];a[x](b)}}else a=[]}else{b=this.w.za();a=[];for(var c=0;c<b[A];c++){var d=b[c];ec(d)?id(a,d):a[x](d)}}return a};Q.ea=function(a,b){Xh(this);Yh(this);a=Zh(this,a);if(this.ia(a)){var c=this.w.qa(a);if(ec(c))this.o-=c[A];else this.o--}this.w.ea(a,b);this.o++;return this};Q.qa=function(a,b){Xh(this);a=Zh(this,a);if(this.ia(a)){var c=this.w.qa(a);return ec(c)?c[0]:c}else return b};
ka(Q,function(){if(this.a)return this.a;if(!this.w)return"";for(var a=[],b=0,c=this.w.Oa(),d=0;d<c[A];d++){var e=c[d],f=Rc(e);e=this.w.qa(e);if(ec(e))for(var h=0;h<e[A];h++){b>0&&a[x]("&");a[x](f);e[h]!==""&&a[x]("=",Rc(e[h]));b++}else{b>0&&a[x]("&");a[x](f);e!==""&&a[x]("=",Rc(e));b++}}return this.a=a[Rb]("")});function Yh(a){delete a.b;delete a.a;a.d&&delete a.d.W}Q.Q=function(){var a=new Nh;if(this.b)a.b=this.b;if(this.a)a.a=this.a;if(this.w)a.w=this.w.Q();return a};
function Zh(a,b){var c=n(b);if(a.c)c=c.toLowerCase();return c}function Uh(a,b){var c=b&&!a.c;if(c){Xh(a);Yh(a);Ah(a.w,function(d,e){var f=e.toLowerCase();if(e!=f){this.remove(e);this.add(f,d)}},a)}a.c=b};function bi(a,b){this.b=new Eh(a);this.a=b?b:"callback";this.va=5E3}var ci=0;
ua(bi[B],function(a,b,c,d){if(!t[Ub][M]){c&&c(a);return k}d=d||"_"+(ci++)[z](36)+nc()[z](36);R._callbacks_||(R._callbacks_={});var e=t[qb]("script"),f=k;if(this.va>0){f=di(d,e,a,c);f=R[Sa](f,this.va)}c=this.b.Q();a=a;var h=c;for(var j in a)if(!a[cb]||a[cb](j))Wh(h,j,a[j]);if(b){b=ei(d,e,b,f);R._callbacks_[d]=b;Wh(c,this.a,"_callbacks_."+d)}je(e,{type:"text/javascript",id:d,charset:"UTF-8",src:c[z]()});b=t[Sb]("head")[0];b[w](e);return{R:d,va:f}});
oa(bi[B],function(a){if(a&&a.R){var b=gc(a.R)?t.getElementById(a.R):a.R;if(b&&b[N]=="SCRIPT"&&typeof R._callbacks_[a.R]=="function"){a.va&&R[Ka](a.va);fi(a.R,b,l)}}});function di(a,b,c,d){return function(){fi(a,b,l);d&&d(c)}}function ei(a,b,c,d){return function(){R[Ka](d);fi(a,b,i);c[Fb](m,arguments)}}function fi(a,b,c){R[Sa](function(){ve(b)},0);if(R._callbacks_[a])if(c)delete R._callbacks_[a];else R._callbacks_[a]=bc};function gi(a){return hi(a||arguments.callee.caller,[])}
function hi(a,b){var c=[];if(ed(b,a))c[x]("[...circular reference...]");else if(a&&b[A]<50){c[x](ii(a)+"(");for(var d=a.arguments,e=0;e<d[A];e++){e>0&&c[x](", ");var f;f=d[e];switch(typeof f){case "object":f=f?"object":"null";break;case "string":f=f;break;case "number":f=n(f);break;case "boolean":f=f?"true":"false";break;case "function":f=(f=ii(f))?f:"[fn]";break;default:f=typeof f}if(f[A]>40)f=f[Vb](0,40)+"...";c[x](f)}b[x](a);c[x](")\n");try{c[x](hi(a.caller,b))}catch(h){c[x]("[exception trying to get caller]\n")}}else a?
c[x]("[...long stack...]"):c[x]("[end]");return c[Rb]("")}function ii(a){a=n(a);if(!ji[a]){var b=/function ([^\(]+)/[Ja](a);if(b){b=b[1];ji[a]=b}else ji[a]="[Anonymous]"}return ji[a]}var ji={};function ki(a,b,c,d,e){this[Jb](a,b,c,d,e)}ki[B].c=0;ki[B].a=k;ki[B].xc=k;var li=0;ki[B].reset=function(a,b,c,d,e){this.c=typeof e=="number"?e:li++;this.h=d||nc();this.b=a;this.f=b;this.d=c;delete this.a;delete this.xc};ki[B].Rc=Xb("b");function mi(a){this.h=a}mi[B].a=k;mi[B].c=k;mi[B].b=k;mi[B].d=k;function ni(a,b){this.name=a;qa(this,b)}ka(ni[B],Yb("name"));var oi=new ni("SEVERE",1E3),pi=new ni("WARNING",900),qi=new ni("CONFIG",700),ri=new ni("FINE",500);mi[B].Rc=Xb("c");function si(a){if(a.c)return a.c;if(a.a)return si(a.a);return k}mi[B].log=function(a,b,c){if(a[Ya]>=si(this)[Ya]){a=this.f(a,b,c);for(b=this;b;){c=b;var d=a;if(c.d)for(var e=0,f=void 0;f=c.d[e];e++)f(d);b=b.a}}};
mi[B].f=function(a,b,c){var d;d=d=new ki(a,n(b),this.h);if(c){d.a=c;var e=d,f;var h=arguments.callee.caller;try{var j,o=c,r=ac("window.location.href");j=typeof o=="string"?{message:o,name:"Unknown error",lineNumber:"Not available",fileName:r,stack:"Not available"}:!o.lineNumber||!o[Mb]||!o.stack?{message:o[bb],name:o[Lb],lineNumber:o.lineNumber||o.line||"Not available",fileName:o[Mb]||o.filename||o.sourceURL||r,stack:o.stack||"Not available"}:o;var y="Message: "+Sc(j[bb])+'\nUrl: <a href="view-source:'+
j[Mb]+'" target="_new">'+j[Mb]+"</a>\nLine: "+j.lineNumber+"\n\nBrowser stack:\n"+Sc(j.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+Sc(gi(h)+"-> ");f=y}catch(s){f="Exception trying to expose exception! You win, we lose. "+s}e.xc=f}return d};function ti(a,b,c){a.log(ri,b,c)}var ui={},vi=k;
function wi(a){if(!vi){vi=new mi("");ui[""]=vi;vi.Rc(qi)}var b=ui[a];if(!(b=b)){a=a;b=new mi(a);var c=a.lastIndexOf("."),d=a[Vb](0,c);c=a[Vb](c+1);d=wi(d);c=c;var e=b,f;f=d;if(!f.b)f.b={};f=f.b;f[c]=e;b.a=d;b=ui[a]=b}return b};var xi=R.window;function yi(){}yi[B].tb=k;function zi(){return Ai(Bi)}var Bi;function Ci(){}U(Ci,yi);function Ai(a){return(a=Di(a))?new ActiveXObject(a):new XMLHttpRequest}function Ei(a){a=Di(a);var b={};if(a){b[0]=i;b[1]=i}return b}Ci[B].a=k;
function Di(a){if(!a.a&&typeof XMLHttpRequest=="undefined"&&typeof ActiveXObject!="undefined"){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b[A];c++){var d=b[c];try{new ActiveXObject(d);return a.a=d}catch(e){}}g(ba("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed"))}return a.a}var Fi=new Ci;Bi=Fi;function Gi(a){this.headers=new Bh;this.a=a||k}U(Gi,$f);Q=Gi[B];Q.T=wi("goog.net.XhrIo");Q.wa=l;Q.F=k;Q.Ob=k;Q.Gc="";Q.Fc="";Q.kb=0;Q.lb="";Q.Vb=l;Q.Cb=l;Q.cc=l;Q.Aa=l;Q.Kb=0;Q.Ja=k;
ua(Q,function(a,b,c,d){if(this.F)g(ba("[goog.net.XhrIo] Object is active with another request"));b=b||"GET";this.Gc=a;this.lb="";this.kb=0;this.Fc=b;this.Vb=l;this.wa=i;this.F=this.a?Ai(this.a):new zi;this.Ob=this.a?this.a.tb||(this.a.tb=Ei(this.a)):Bi.tb||(Bi.tb=Ei(Bi));this.F.onreadystatechange=T(this.Kc,this);try{ti(this.T,Hi(this,"Opening Xhr"));this.cc=i;this.F.open(b,a,i);this.cc=l}catch(e){ti(this.T,Hi(this,"Error opening Xhr: "+e[bb]));Ii(this,5,e);return}a=c||"";var f=this.headers.Q();d&&
Ah(d,function(j,o){f.ea(o,j)});b=="POST"&&!f.ia("Content-Type")&&f.ea("Content-Type","application/x-www-form-urlencoded;charset=utf-8");Ah(f,function(j,o){this.F.setRequestHeader(o,j)},this);try{if(this.Ja){xi[Ka](this.Ja);this.Ja=k}if(this.Kb>0){ti(this.T,Hi(this,"Will abort after "+this.Kb+"ms if incomplete"));this.Ja=xi[Sa](T(this.va,this),this.Kb)}ti(this.T,Hi(this,"Sending request"));this.Cb=i;this.F[pb](a);this.Cb=l}catch(h){ti(this.T,Hi(this,"Send error: "+h[bb]));Ii(this,5,h)}});
Q.dispatchEvent=function(a){return Gi.s[H][L](this,a)};Q.va=function(){if(typeof Zb!="undefined")if(this.F){this.lb="Timed out after "+this.Kb+"ms, aborting";this.kb=8;ti(this.T,Hi(this,this.lb));this[H]("timeout");this[Qa](8)}};function Ii(a,b,c){a.wa=l;if(a.F){a.Aa=i;a.F[Qa]();a.Aa=l}a.lb=c;a.kb=b;Ji(a);Ki(a)}function Ji(a){if(!a.Vb){a.Vb=i;a[H]("complete");a[H]("error")}}
Q.abort=function(a){if(this.F){ti(this.T,Hi(this,"Aborting"));this.wa=l;this.Aa=i;this.F[Qa]();this.Aa=l;this.kb=a||7;this[H]("complete");this[H]("abort");Ki(this)}};Q.r=function(){if(this.F){if(this.wa){this.wa=l;this.Aa=i;this.F[Qa]();this.Aa=l}Ki(this,i)}Gi.s.r[L](this)};Q.Kc=function(){!this.cc&&!this.Cb&&!this.Aa?this.Od():Li(this)};Q.Od=function(){Li(this)};
function Li(a){if(a.wa)if(typeof Zb!="undefined")if(a.Ob[1]&&Mi(a)==4&&Ni(a)==2)ti(a.T,Hi(a,"Local request error detected and ignored"));else if(a.Cb&&Mi(a)==4)xi[Sa](T(a.Kc,a),0);else{a[H]("readystatechange");if(Mi(a)==4){ti(a.T,Hi(a,"Request complete"));a.wa=l;if(Oi(a)){a[H]("complete");a[H]("success")}else{a.kb=6;var b=a,c;try{c=Mi(a)>2?a.F.statusText:""}catch(d){ti(a.T,"Can not get status: "+d[bb]);c=""}b.lb=c+" ["+Ni(a)+"]";Ji(a)}Ki(a)}}}
function Ki(a,b){if(a.F){var c=a.F,d=a.Ob[0]?bc:k;a.F=k;a.Ob=k;if(a.Ja){xi[Ka](a.Ja);a.Ja=k}b||a[H]("ready");try{c.onreadystatechange=d}catch(e){a.T.log(oi,"Problem encountered resetting onreadystatechange: "+e[bb],void 0)}}}function Oi(a){switch(Ni(a)){case 0:case 200:case 204:case 304:return i;default:return l}}function Mi(a){return a.F?a.F.readyState:0}function Ni(a){try{return Mi(a)>2?a.F.status:-1}catch(b){a.T.log(pi,"Can not get status: "+b[bb],void 0);return-1}}
function Hi(a,b){return b+" ["+a.Fc+" "+a.Gc+" "+Ni(a)+"]"};var Pi;
(function(){function a(j){j=j[nb](/[\d]+/g);la(j,3);return j[Rb](".")}var b=l,c="";if(aa[Fa]&&aa[Fa][A]){var d=aa[Fa]["Shockwave Flash"];if(d){b=i;if(d.description)c=a(d.description)}if(aa[Fa]["Shockwave Flash 2.0"]){b=i;c="2.0.0.11"}}else if(aa.mimeTypes&&aa.mimeTypes[A]){if(b=(d=aa.mimeTypes["application/x-shockwave-flash"])&&d.enabledPlugin)c=a(d.enabledPlugin.description)}else try{d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7");b=i;c=a(d.GetVariable("$version"))}catch(e){try{d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");b=
i;c="6.0.21"}catch(f){try{d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");b=i;c=a(d.GetVariable("$version"))}catch(h){}}}Pi=c})();function Qi(a,b){this.ob=new Eh(a);if(b)for(var c in b)if(b[c]!==q[B][c]){var d=this.ob,e=c,f=b[c];Th(d);delete d.W;d.a.ea(e,f)}}U(Qi,Mc);za(Qi[B],function(){return i});va(Qi[B],function(){return this[Nb]()});ua(Qi[B],function(){return k});oa(Qi[B],function(){});function Ri(a,b,c){Qi[L](this,a,b);this.a=new bi(this.ob[z](),c)}U(Ri,Qi);ua(Ri[B],function(a,b){this.a.va=-1;return this.a[pb](a,b)});oa(Ri[B],function(a){this.a[Oa](a)});
function Si(a,b,c){Qi[L](this,"",c);this.d=a;this.f=b;this.h=Fg(c);this.b={};R._fhr_callback_||(R._fhr_callback_={});this.d=a;this.c=$c(Pi,"9.0")>=0}U(Si,Qi);var Ti=0;function Ui(){return"I"+(Ti++)[z](36)+nc()[z](36)}
function Vi(a){if(a.c){if(!a.k){a.k=ne("div",{style:"position:absolute;top:-1000px;height:1px;width:1px"});t[J][w](a.k);a.R="f"+Ui();var b={id:a.R,src:a.d},c=a.k;if(V){b=b;var d=new kg;d.G('<object id="',b.id,'" name="',b.id,'" width="400" height="500" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="//download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab"><param name="movie" value="',b.src,'"/><param name="allowScriptAccess" value="always"/></object>');b=d[z]()}else{b=b;d=new kg;
d.G('<object id="',b.id,'" name="',b.id,'" width="400" height="500" type="application/x-shockwave-flash" data="',b.src,'"><param name="allowScriptAccess" value="always"/></object>');b=d[z]()}pa(c,b)}if(!a.a)a.a=V?p[a.R]:t[a.R]}}Q=Si[B];za(Q,Yb("c"));va(Q,function(){Vi(this);return this.c&&this.a&&this.a[tb]&&this.a[tb]()});
ua(Q,function(a,b){Vi(this);if(!this.a||!this.a[pb])return k;var c="cb"+Ui();R._fhr_callback_[c]=b;var d=this.a[pb](this.f,"_fhr_callback_."+c,this.h,Fg(a));if(d<0){delete R._fhr_callback_[c];return k}var e=Ui();this.b[e]={Yc:c,na:d};return e});oa(Q,function(a){Vi(this);var b=this.b[a];if(b){this.a[Oa](b.na);delete R._fhr_callback_[b.Yc];delete this.b[a]}});
Q.r=function(){Si.s.r[L](this);for(var a in this.b)if(this.b[a]!==q[B][a]){var b=this.b[a];this.a[Oa](b.na);delete R._fhr_callback_[b.na]}if(this.k){ve(this.k);this.a=this.b=this.k=k}};function Wi(a,b){Qi[L](this,a,b);this.b={};this.a=this.c=0;if(!Hd){if(p.XMLHttpRequest){var c=new XMLHttpRequest;if("withCredentials"in c)this.a=1}if(!this.a&&p.XDomainRequest)this.a=2}}U(Wi,Qi);za(Wi[B],function(){return!!this.a});
ua(Wi[B],function(a,b){var c=Jg(),d=++this.c,e={};if(this.a==1){e.Ka=new Gi;mf(e.Ka,"complete",T(function(){if(!e.Tb){if(Oi(e.Ka)){var f=b,h;var j=e.Ka;try{h=j.F?j.F.responseText:""}catch(o){ti(j.T,"Can not get responseText: "+o[bb]);h=""}f(h)}else b(k,"IO_ERROR");Xi(this,d)}},this));e.Ka[pb](this.ob[z](),"POST",Fg(a),{"Content-Type":"application/x-www-form-urlencoded"})}else{e.fa=new XDomainRequest;e.fa.timeout=2E4;e.fa.onload=T(function(){if(!e.Tb){b(e.fa.responseText);Xi(this,d)}},this);e.fa.onerror=
e.fa.ontimeout=T(function(){if(!e.Tb){b(k,"IO_ERROR");Xi(this,d)}},this);e.fa.open("POST",this.ob[z]());e.fa[pb](Fg(a))}this.b[d]=e;Kg(c);return d});oa(Wi[B],function(a){var b=this.b[a];if(b){b.Tb=i;b.fa&&b.fa[Qa]();Xi(this,a)}});function Xi(a,b){var c=a.b[b];if(c){if(c.Ka){c.Ka.p();c.Ka=k}else if(c.fa)c.fa=k;delete a.b[b]}}Wi[B].r=function(){Wi.s.r[L](this);for(var a in this.b)this[Oa](a)};function Yi(a){var b={anno:3,client:yc,format:"html",v:"1.0"};a&&(b.ssl=1);if(xc)b.scid=xc;a=a?"https://":"http://";this.J=k;this.Ma={ub:Zi,Hc:300};this.b=new Ri(a+Dc,{client:yc},"cb");b=[{N:new Wi(a+zc+"/translate_a/t",b),ub:$i,fc:30720,Ic:61440,mb:-1,Pc:0,wb:l},{N:new Si(a+Cc,"translate",b),Mc:100,ub:$i,fc:30720,Ic:61440,mb:-1,Pc:0,wb:l}];this.c=new aj(b);this.a=l;for(a=0;a<b[A];++a)this.a=this.a||b[a].N[Nb]();this.a||Gg("te_au")}U(Yi,Mc);function aj(a){this.b=a}
aj[B].start=function(a){this.La=a;this.a=0;bj(this)};function bj(a){if(a.a>=a.b[A])a.La(k);else{var b=a.b[a.a++];if(b.Mc)(new Ag(T(b.N[tb],b.N),T(function(c){c?this.La(b):bj(this)},a),30,b.Mc)).go();else b.N[tb]()?a.La(b):bj(a)}}
function $i(a){return function(b){if(b)try{var c=b[G]("\u0000");if(c>=0)b=b[Vb](0,c);var d=eval("("+b+")")}catch(e){d=k;Gg("te_afbr")}if(d){b=a;d=d;if(dc(d)!="array")c=[[d,200]];else if(dc(d[0])!="array")if(d[A]==2)c=[[d[0],200,d[1]],[d[1],200,d[1]]];else{c=[];for(var f=0;f<d[A];++f)c[f]=[d[f],200]}else{c=[];for(f=0;f<d[A];++f)c[f]=[d[f][0],200,d[f][1]]}d=c;b(d,200)}else a([],500)}}function Zi(a){return function(b){if(b)try{var c=eval("("+b+")")}catch(d){c=k}a(c&&c[1]||m)}}Q=Yi[B];
Q.Gd=function(a){if(!this.d){this.d=i;this.c.start(T(function(b){if(b){this.J=b;this.Ma.N=b.N}a()},this))}};za(Q,Yb("a"));va(Q,function(){return this.J!==k&&this.J.N!==k&&this.J.N[tb]()});Q.translate=function(a,b,c,d,e,f){a=this.J.ub(a);b={q:b,sl:c,tl:d};b.tc=e;if(f)b.ctt=1;return this.J.N[pb](b,a)};function cj(a){return a.J.wb?a.J.fc-a.J.N.ob.Q()[z]()[A]:a.J.fc}Q.r=function(){Yi.s.r[L](this);if(this.J){this.J.N.p();this.J.N=k}this.Ma.N=k;this.b.p();this.b=k};function dj(a,b){this.d=a;this.l=!!b;this.a=this.k=0;this.b=this.c=-1;this.f=this.j=this.h=0}var ej=sg([".",",",";",":","\\?","!"]),fj=sg([34,35,36,37,38,43,44,47,58,59,60,61,62,63,64,91,92,93,94,96,123,124,125,127]);function gj(a,b){if(!a.l)return 1;if(b<=127){if(b<=32||fj[b])return 3;return 1}else if(b<=2047)return 6;else if(b<=65535)return 9;return 12}
function hj(a,b){a.l&&(b-=12);for(var c="",d=a.k;d<a.d[A];++d){var e=a.d.charAt(d),f=e.charCodeAt(0);a.h+=gj(a,f);if(ej[e]){a.b=d;a.j=a.h}else if(e==" "){a.c=d;a.f=a.h}if(a.h>=b){if(a.b>=0){c=a.d[Ab](a.a,a.b+1);a.h-=a.j;a.a=a.b+1;if(a.b>=a.c){a.c=-1;a.f=0}else a.f-=a.j;a.b=-1;a.j=0}else if(a.c>=0){c=a.d[Ab](a.a,a.c+1);a.h-=a.f;a.a=a.c+1;if(a.c>=a.b)a.b=-1;else a.j-=a.f;a.c=-1;a.f=0}else{c=a.d[Ab](a.a,d+1);a.h=0;a.a=d+1;a.b=a.c=-1;a.f=a.j=0}a.k=d+1;return c}}if(a.a<a.d[A]){c=a.d[Ab](a.a);a.a=a.d[A]}return c}
function ij(a,b,c,d,e){this.O=a;this.f=b;this.qc=c;this.K=new ih(d?T(this.Vd,this):k,c,e);this.m=k;this.B=l;this.j="auto";this.d="en";this.pc=l;this.l={};this.c={};this.ke=[]}U(ij,Mc);Q=ij[B];
Q.zc=function(){var a=this.cb,b;if(b=a.bb>0){b=a;var c;c=a.Eb;var d=oh(this.K,c);if(d)c=d;else if(this.Pb[A]){this.K[Jb](this.Pb[Ha](),this.cb.Vc);c=oh(this.K,c)}else c=k;b=b.Y=c}if(b){this.m[x](a.Y);var e=this.f.J.wb?a.Y.B:a.Y.ja[A];this.eb+=a.Y.ja[A];if(this.l&&this.l[a.Y.ja]){this.b.add(T(this.Rb,this,a.Y));a.bb-=e}else if(e>a.X){b=a.Y.ja;c=new dj(b);d=[];var f="";if(a.Ta)for(;jj(a)&&e>a.X;);for(;f=hj(c,a.X);){e={na:k,Y:a.Y,Ra:d,content:f,nb:l};d[x](e);this.a[x](e);a.bb-=f[A];if(a.bb<=0){e.rc=
b[Ab](c.a);break}else jj(a)}}else{if(!a.Ta||e>a.Ub||a.hc>=a.mb&&a.mb>0){if(a.Ta){kj(this);jj(a);a.Ub=a.X}a.Ta={na:k,ka:[],nb:l};this.a[x](a.Ta);a.hc=0}a.Ta.ka[x](a.Y);a.Ub-=e+this.f.J.Pc;a.bb-=e;a.hc++}this.h.add(T(this.zc,this))}else{this.h=k;if(this.a[A]==0)this.b.add(T(this.Wb,this));else this.D==0&&kj(this);this.b.go()}};Q.Vd=function(a){var b=Nc(a[zb]);if(!(b[G]("javascript:")==0||b[G]("#")>=0)){this.db[x](a[zb]);this.k[x](a);a.href=b+"#googtrans/"+this.j+"/"+this.d}};
function kj(a){for(var b=3+a.Fa;a.D<a.a[A]&&a.D<b;++a.D){var c=a,d=a.D,e=c.a[d],f=e.Sc||c.j,h=[];if(e.ka)for(var j=0;j<e.ka[A];++j)h[x](e.ka[j].ja);else h[x](e.content);e.na=c.f[Gb](T(c.Dd,c,d),h,f,c.d,d+1,c.pc)}}
Q.Dd=function(a,b,c){a=this.a[a];if(this.B&&a){if(c!=200)this.b.add(T(this.M,this,this.H,l,i));else if(a.ka){var d=[];for(c=0;c<b[A]&&c<a.ka[A];++c)if(b[c]&&b[c][1]&&b[c][1]==200){var e=b[c][0],f=b[c][2]&&b[c][2]==this.d;this.b.add(T(this.Rb,this,a.ka[c],e,f));if(b[c][2]){f=b[c][2];this.c[f]||(this.c[f]=0);this.c[f]+=e[A]}}else d[x](a.ka[c]);this.j=="auto"&&d[A]>0&&!a.nb&&this.a[x]({na:k,Sc:"en",ka:d,nb:i})}else if(b&&b[0]){a.Uc=b[0][0];if(b[0][2]){f=b[0][2];if(this.c[f])this.c[f]=0;this.c[f]=b[0][0][A]}b=
[];for(c=0;c<a.Ra[A];++c)if(typeof a.Ra[c].Uc=="string"){b[x](a.Ra[c].Uc);a.Ra[c].rc&&b[x](a.Ra[c].rc)}else break;b[A]==a.Ra[A]&&this.b.add(T(this.Rb,this,a.Y,b[Rb]("")))}else if(this.j=="auto"&&!a.nb){a.Sc="en";a.nb=i;a.na=k;this.a[x](a)}this.Fa++;(b=this.Fa==this.a[A])&&this.b.add(T(this.Wb,this));this.h||this.b.go();kj(this)}};
Q.Rb=function(a,b,c){if(b){var d=a,e=b;b=this.l;c=c;d.k=i;d.c=[];d.c.cd=c;if(!c){c=t[qb]("div");W(c,l);pa(c,e[G]("<i>")>=0?e:"<b>"+e+"</b>");t[J][w](c);e=k;for(var f=c[M];f;f=f[Ob])if(f[N]=="I")d.c[x](e={Lc:Ce(f),aa:[]});else if(f[N]=="B"){e||d.c[x](e={Lc:"",aa:[]});if(d.a[A]==1)e.aa[x]({index:0,text:Yc(Ce(f))});else{for(var h={},j=-1,o=f[M];o;o=o[Ob])if(o.attributes&&o.attributes.i){j=ea(o.attributes.i[Tb],10);if(j!=NaN){h[j]||(h[j]="");h[j]+=Ce(o)}}else if(o[F]==3){h[j]||(h[j]="");h[j]+=o[Tb]}for(j in h)h[j]!==
q[B][j]&&j>=0&&j<d.a[A]&&e.aa[x]({index:j,text:Yc(h[j])});if(h[-1])if(e.aa[A]==0&&h[-1])e.aa[x]({index:0,text:Yc(h[-1])});else e.aa[0].text=Yc(h[-1])+e.aa[0][Ma]}e=k}c[O][ib](c)}b&&(b[d.ja]=d.c);Wg(d)}else Wg(a,this.l);this.Qb+=a.ja[A];a=u.min(u[Pa](this.Qb*100/this.eb),100);if(this.H!=a){this.H=a;this.M(this.H,l)}};Q.Wb=function(){this.B=l;this.M&&this.M(100,i);this.a=k;this.D=this.Fa=0;this.M=k;this.H=this.Qb=this.eb=0};
function lj(a){if(a.B){for(var b=0;b<a.a[A];++b)a.f.J.N[Oa](a.a[b].na);a.Wb()}if(a.h){a.h[Oa]();a.h=k}if(a.b){a.b[Oa]();a.b=k}if(a.m){for(b=0;b<a.m[A];++b)a.m[b].p();a.m=k}if(a.k){for(b=0;b<a.k[A];++b)a.k[b].href=a.db[b];a.k=k;a.db=k}if(a.Ia){var c=[][Wa](a.O);for(b=0;b<c[A];++b)de(c[b],a.Ia);a.Ia=k}}
Q.translate=function(a,b,c){if(a!=this.j||b!=this.d){lj(this);this.l={}}else if(this.B)return;this.M=c;this.H=this.Qb=this.eb=0;this.b=new tg(0,0,50);this.B=i;this.j=a;this.d=b;if(this.qc){c=this.qc;b=b;a&&(c.l=a);b&&(c.m=b)}this.a=[];this.m=[];this.D=this.Fa=0;this.k=[];this.db=[];a=860;for(var d in this.l)if(this.l[d]!==q[B][d]){a=cj(this.f);break}this.cb={X:a,Ub:a,Eb:cj(this.f),bb:this.f.J.Ic,hc:0,mb:this.f.J.mb,Vc:this.f.J.wb,Ta:k,Y:k};this.Ia=ig[Ga](this.d)?"translated-rtl":"translated-ltr";
a=[][Wa](this.O);for(d=0;d<a[A];++d)ce(a[d],this.Ia);this.Pb=[][Wa](this.O);this.K[Jb](this.Pb[Ha](),this.cb.Vc);this.h=new tg(0,0,50);this.h.add(T(this.zc,this));this.h.go()};function jj(a){var b=a.X;if(a.X<a.Eb){a.X*=6;if(a.X>a.Eb)a.X=a.Eb}var c=a.bb+1024;if(a.X>c)a.X=c;return b!=a.X}xa(Q,function(){lj(this)});Q.r=function(){ij.s.r[L](this);lj(this);this.O=this.K=k};function mj(){this.b=1;this.a={}}U(mj,Mc);var nj=new mj;function oj(a,b){if(a.a[b]){a.a[b][Db]();a.a[b].p();a.a[b]=k}}mj[B].r=function(){for(var a in this.a)if(this.a[a]!==q[B][a]){var b;b=a;var c=ga(b);b=c==0&&/^[\s\xa0]*$/[Ga](b)?NaN:c;oj(this,b)}this.b=1;this.a={}};function pj(a,b,c,d){this.h=b;this.k=c;this.f=d;this.d=l;this.a=new Yi(a||l);a=new ug;b=new yg(T(this.a.Gd,this.a,vg(a)));this.zb=zg(b,xg(a,T(this.zb,this)));this.yb=zg(b,xg(a,T(this.yb,this)));this.Lb=zg(b,xg(a,T(this.Lb,this)));xa(this,zg(b,xg(a,T(this[Db],this))));b.oa();a.oa();this.b=nj;this.c=this.nc(t[Ub])}U(pj,Mc);Q=pj[B];va(Q,function(){return this.a[Nb]()});function qj(a){Gg(a.a[Nb]()?"te_afas":"te_afau")}Q.zb=function(a,b){if(this.a[tb]())this.a.b[pb](b?{hl:b}:{},a);else{qj(this);a(k,i)}};
Q.yb=function(a){var b=t[Ub].lang;if(b)a(b);else if(this.a[tb]()){var c=new fh(t[J],l,l,1,1);b=[];try{for(var d=0,e=this.a.Ma.Hc;b[A]+d<e;){var f=c.Da();if(c.V==1&&qh(f))gh(c);else if(f[F]==3){var h=Nc(f[Tb][E](/\xa0|[ \t]+/g," "));if(h){b[x](h);d+=h[A]}}}}catch(j){if(j!=dh)g(j)}e=this.a;b=b[Rb](" ");a=e.Ma.ub(a);b={q:b[Ab](0,e.Ma.Hc)};b.sl="auto";b.tl="en";e.Ma.N[pb](b,a)}else{qj(this);a(k,i)}};
Q.jd=function(a){var b=k;a=a!=k?a:this.c;a!=-1&&(b=this.b.a[a]);a="";if(!b)return a;if(b.j!="auto")return b.j;var c=0;if(b.c)for(var d in b.c)if(b.c[d]!==q[B][d])if(b.c[d]>c){c=b.c[d];a=d}return a};Q.Lb=function(a,b,c,d){if(this.a[tb]()){if(d!==m&&typeof d=="number")d=d;else{d=d||t[Ub];if(this.b.a[this.c].O!=d){this[Db]();oj(this.b,this.c);this.c=this.nc(d)}d=this.c}if(d=this.b.a[d]){d.pc=this.d;d[Gb](a,b,c)}}else{qj(this);c(0,l,i)}};Q.$d=function(a){a=a!=k?a:this.c;return a==-1||!this.b.a[a]?l:this.b.a[a].B};
Q.Qc=Xb("d");xa(Q,function(a){if(this.a[tb]()){a=a!=k?a:this.c;a!=-1&&this.b.a[a]&&this.b.a[a][Db]()}});Q.r=function(){pj.s.r[L](this);this.a.p();this.a=k;this.b.p();this.c=m};Q.nc=function(a){var b=this.b;b.a[b.b]=new ij(a,this.a,this.h,this.k,this.f);return a=b.b++};Q.Zd=function(a){oj(this.b,a)};function rj(a,b){if(dc(a)=="string"){b=a;a={}}if(dc(b)=="string")b=gc(n(b))?t.getElementById(n(b)):n(b);this.k=b;var c=q(a);this.c="auto";var d;if(!(d=p.parent!=p)){if(d=!p.external||!p.external.googleToolbarVersion||fa(p.external.googleToolbarVersion)<6.2){if(d=!p.gtbExternal||!p.gtbExternal.isTranslateEnabled||!p.gtbExternal.isTranslateEnabled()){d=(d=aa.appVersion&&aa.appVersion[nb](/\sChrome\/((\d+)\.(\d+)\.[\d\.]+)\s/))&&d[2]&&d[3]?ga(d[2])*1E3+ga(d[3])>=4001:l;d=!d}d=d}d=d}this.e={rb:d,Sb:k,
sb:k,dc:[],yc:[],bd:l,Xa:l,Nb:l,Ac:l,Xb:"",Ua:0};d=p[Za].protocol=="https:";this.Fa={A:Gc,Ha:d?"The content of this secure page will be sent to Google for translation using a secure connection.":k};this.e.Nb=d;this.O={A:Gc,ib:k};if(c){"autoDisplay"in c&&(this.e.rb=this.e.rb&&ca(c.autoDisplay));"multilanguagePage"in c&&(this.e.Xa=ca(c.multilanguagePage));"gaTrack"in c&&(this.e.Ac=ca(c.gaTrack));"layout"in c&&(this.e.Ua=c.layout);if(c.pageLanguage)this.e.Fb=Eg(c.pageLanguage);if("useSecureConnection"in
c){this.e.Nb=!!c.useSecureConnection;this.Fa.Ha=this.e.Nb?"The content of this secure page will be sent to Google for translation using a secure connection.":k}if(c.includedLanguages)this.e.dc=c.includedLanguages[Ua](",");if(c.excludedLanguages)this.e.yc=c.excludedLanguages[Ua](",");if(this.e.Fb)this.c=this.e.Fb;if(c.gaId)this.e.Xb=c.gaId;this.O.ib=ga(c.floatPosition)||this.O.ib}sj(this);c={$:xc?1:0,Ga:i,se:Lc,ba:["client","u","scid"]};this.db=new Ng(c);c={client:yc,u:p[Za][zb],scid:xc};this.db.k=
c||{};this.m=new pj(this.e.Nb,this.db);this.f=new Wf(this);this.H=l;this.Ia=!this.e.rb&&!this.O.ib&&!this.k;X(this.f,p,"unload",this.p);this.j=new ug(T(this.xd,this));this.D=new ug(T(this.zd,this));this.K=new yg(T(this.Jd,this));this.a=new rh(this.Fa);this.m.zb(vg(this.j,T(this.wd,this)),pc);if(this.k){this.b=new vh(this.e);X(this.f,this.b,"load",vg(this.j));X(this.f,this.b,"chg_tgt_lang",zg(this.K,xg(this.D,T(this.vd,this))));this.b.ma(this.k)}else if(this.O.ib){this.h=new xh(this.O);X(this.f,this.h,
"load",vg(this.j));X(this.f,this.h,"clk_trans",zg(this.K,xg(this.D,T(this.td,this))));this.h.ma()}!this.e.Fb&&this.e.bd&&this.m.yb(vg(this.j,T(this.rd,this)));this.j.oa()}U(rj,Mc);
function sj(a){function b(f,h){var j=ha(f[E](/\+/g," "))[nb]("^\\((([a-zA-Z\\-_]*)\\|)?([a-zA-Z\\-_]*)\\)|^/(([a-zA-Z\\-_]*)/)?([a-zA-Z\\-_]*)");if(j)if(j[3]){h.e.Sb=j[2];h.e.sb=j[3];return i}else if(j[6]){h.e.Sb=j[5];h.e.sb=j[6];return i}return l}for(var c=[function(){var f=p[Za][zb][nb](/#.*googtrans(.*)/);return f&&f[1]},function(){var f=t.cookie[nb](/(^|; )googtrans=(.*?)(;|$)/);return f&&f[2]}],d=0;d<c[A];++d){var e=c[d]();if(e&&b(e,a))break}}
function tj(a,b,c){for(a=p[Za].hostname[Ua](".");a[A]>2;)a[Ha]();a=";domain="+a[Rb](".")+";path=/";if(!b&&!c){b=new Date;b.setTime(b.getTime()-1);b="googtrans=none;expires="+b.toGMTString()}else b=b?"googtrans=/"+b+"/"+c:"googtrans=/"+c;t.cookie=b;try{t.cookie=b+a}catch(d){}}Q=rj[B];
Q.wd=function(a){this.d=Eg(pc);this.B=a||{};this.l={};this.M={};a=!this.e.dc[A];var b=sg(this.e.dc),c=sg(this.e.yc);this.l[pc]="";this.M[pc]="";for(var d in this.B.tl)if(this.B.tl[d]!==q[B][d])if((a||d in b)&&!(d in c)){this.M[d]=this.B.tl[d];if(d!=this.e.Fb||this.e.Xa)this.l[d]=this.B.tl[d]}this.l[pc]||delete this.l[pc];this.M[pc]||delete this.M[pc];var e;d=this.B.sl;a={};for(e in d)a[e]=d[e];this.cb=e=a};Q.rd=function(a){if(a)this.c=Eg(a)};
Q.xd=function(){delete this.j;if(this.B){this.c=this.c||this.e.Sb;this.d=this.e.sb||this.d;var a=this.e.rb&&this.c!=this.d&&!(this.c in sc);if(this.c=="zh-TW")this.c="zh-CN";if(!this.cb[this.c]){a=l;this.c="auto"}if(!this.l[this.d]){a=l;if(this.l.en)this.d="en";else for(var b in this.l)if(this.l[b]!==q[B][b]){this.d=b;break}}if(this.b){var c=this.l,d={"":"Select Language"};for(b in c)if(c[b]!==q[B][b])d[b]=c[b];this.b.kc(d,this.M);this.b.U("")}if(!rc&&a)if(this.e.sb)zg(this.K,xg(this.D,T(this.Ib,
this,i,i)))[L]();else{this.H=i;zg(this.K,xg(this.D,T(this.Ib,this)))[L]();Gg("te_ap",{sl:this.c})}else{this.h&&this.h.P(i);this.b&&this.b.P(i)}p.google[Gb].TranslateService&&this.ab(l);this.K.oa()}};
Q.zd=function(){var a=this.a,b=this.cb;a.I&&a.I.ta(b);a.l=b;this.a.kc(this.l,this.M);sh(this.a,this.c);this.a.U(this.d);X(this.f,this.a,"clk_confirm",this.pd);X(this.f,this.a,"clk_cancel",this.od);X(this.f,this.a,"clk_restore",this.$b);X(this.f,this.a,"clk_close",this.Zb);X(this.f,this.a,"clk_no_ap",this.qd);X(this.f,this.a,"chg_src_lang",this.Dc);X(this.f,this.a,"chg_tgt_lang",this.Dc);this.b&&this.b.P(i)};Q.Jd=function(){X(this.f,this.a,"load",vg(this.D));this.a.ma();this.D.oa()};
Q.r=function(){this.m[Db]();rj.s.r[L](this);this.m.p();this.f.p();this.f=k;this.a&&this.a.p();this.a=k;this.h&&this.h.p();this.h=k;this.b&&this.b.p();this.k=this.b=k};Q.pd=function(){if(!(!this.a.ga()||!this.e.Xa&&this.c==this.a.ca())){this.H&&Gg("te_apt",{sl:this.c});uj(this,l);this.b&&this.b.U(this.a.ca())}};Q.od=function(){if(this.a.ga()){vj(this);th(this.a,0);this.b&&this.b.U("")}};Q.$b=function(){if(this.a.ga()){vj(this);th(this.a,0)}this.b&&this.b.U("")};
Q.Zb=function(){if(this.a.ga()){if(this.H){this.H=l;Gg("te_apc",{sl:this.c})}vj(this);this.a.P(l);this.b&&this.b.U("");this.h&&this.h.P(i)}};Q.qd=function(){if(this.a.ga()){Gg("te_apr",{sl:this.c});this.H=l;this.Zb();if(this.Ia){var a=this.onTurnOffLanguageClick;try{dc(a)=="function"&&a[Fb](this,[])}catch(b){}}}};
Q.Dc=function(){if(this.a.ga())if(!this.e.Xa&&this.c==this.a.ca())this.$b();else{this.c=(this.a.I?this.a.I.Ab():"")||this.c;this.d=this.a.ca();if(this.a.hb==2){this.b&&this.b.U(this.a.ca());uj(this)}}};Q.Ib=function(a,b){if(!this.a.ga()){this.h&&this.h.P(l);a?uj(this,b):th(this.a,0,i,this.H||this.Ia)}};Q.Xd=function(a,b){zg(this.K,xg(this.D,T(this.Ib,this,a,b)))[L]()};Q.td=function(){this.Ib(this.a.hb==2)};
Q.vd=function(){if(this.b.ca())if(!this.e.Xa&&this.c==this.b.ca())this.$b();else{this.d=this.b.ca();this.a.U(this.d);uj(this)}else this.b.U(this.d)};
function uj(a,b){if(p.google[Gb].TranslateService)try{var c=p.google[Gb].TranslateService.getInstance();c[Db]()}catch(d){}a.H=l;!b&&a.c in sc&&Gg("te_ape",{sl:a.c});uh(a.a,0);th(a.a,1,i);a.m.Qc(!!b);p[Sa](T(a.m.Lb,a.m,a.e.Xa?"auto":a.c,a.d,T(a.Cd,a),k),0);if(a.e.Ac&&p._gaq&&p._gat)try{a.e.Xb?p._gat._getTracker(a.e.Xb)._trackEvent("Google Website Translator","Translate",a.d):p._gat._getTrackerByName()._trackEvent("Google Website Translator","Translate",a.d)}catch(e){}}
Q.Cd=function(a,b,c){dc(this.eb)=="function"&&this.eb();if(!(!this.a.ga()||this.a.hb!=1))if(c){vj(this);th(this.a,-1,i)}else{uh(this.a,a);if(b){this.b&&this.b.U(this.d);sh(this.a,this.c);th(this.a,2);tj(this,this.c,this.d)}}};function vj(a){tj(a);p[Sa](T(a.m[Db],a.m,k),0)}Q.ab=function(a){a||this.Zb();this.b&&this.b.ab(a);this.h&&this.h.P(a)};function wj(a){if(a){a=n(a);a=a[Ua](".");if(a[A]){for(var b=p,c=0;c<a[A];++c){var d=a[c];if(!d||!(d in b))return;b=b[d]}return b}}}function xj(){for(var a in q[B]){od=function(d,e,f){for(var h in d)d[h]!==q[B][h]&&e[L](f,d[h],h,d)};break}var b=nc(),c=wj(qc);if(c&&dc(c)=="function")tc==1?c():function d(){var e=t.readyState;dc(e)=="undefined"||e=="complete"||nc()-b>=2E4?c():p[Sa](d,500)}()};if(tc==1){var $=k,yj=function(a){if(!$){var b=p[Za].protocol=="https:";if(a&&"useSecureConnection"in a)b=!!a.useSecureConnection;a={formMode:0,showLogo:i,suggestUrl:Lc,clientName:yc,pageUrl:p[Za][zb]};a=new Ng(a);$=new pj(b,a);$.constructor=m;va($,$[tb]);$.getSupportedLanguages=$.zb;$.getPageLanguage=$.yb;$.getDetectedLanguage=$.jd;$.createContext=$.nc;$.disposeContext=$.Zd;$.setClickThrough=$.Qc;$.translatePage=$.Lb;xa($,$[Db]);$.isTranslating=$.$d}return $};yj.getInstance=function(){return $};$b("google.translate.TranslateService",
yj,void 0);Gg("te_li")}else{var zj=k,Aj=function(a,b){if(!zj){zj=new rj(a,b);zj.constructor=m}return zj};Aj.getInstance=function(){return zj};$b("google.translate.TranslateElement",Aj,void 0);rj[B].dispose=rj[B].p;rj[B].showBanner=rj[B].Xd;rj[B].setEnabled=rj[B].ab;$b("google.translate.TranslateElement.FloatPosition",yh,void 0);yh.TOP_LEFT=1;yh.TOP_RIGHT=2;yh.BOTTOM_RIGHT=3;yh.BOTTOM_LEFT=4;$b("google.translate.TranslateElement.InlineLayout",wh,void 0);wh.VERTICAL=0;wh.HORIZONTAL=1;wh.SIMPLE=2}xj();})()
